### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by Stefankoff** [AppiumTestDistribution/AppiumTestDistribution#1025]
I have an existing project with cross platform tests, using your plugins device-farm, appium-wait-plugin, appium-dasboard.
I want to have remote tests run and parallel execution with your AppiumTestDistribution tool, can you some advices how to do that. I have already add dependncy  
` <dependency>
   <groupId>com.github.saikrishna321</groupId>
   <artifactId>AppiumTestDistribution</artifactId>
   <version>12.0.3</version>
 </dependency>`
and create the config and caps folders with files. 
caps `{
  "android": {
    "platformName": "android",
    "automationName": "UiAutomator2",
    "uiautomator2ServerInstallTimeout": 120000,
    "adbExecTimeout": 140000,
    "appPackage": "com.my.app",
    "app": "path to my app",
    "deviceName": "android",
    "noSign": true
  },
  "serverConfig" : {
    "server": {
      "use-plugins": ["appium-dashboard", "device-farm", "element-wait"],
      "plugin": {
        "device-farm": {
          "platform": "android",
          "skipChromeDownload": true
        }
      }
    }
  }
}`

Create runner class with trial methods 
`package tests;

import com.appium.manager.ATDRunner;
import org.testng.annotations.Test;

import java.util.ArrayList;
import java.util.List;

public class Runner {

    @Test
    public void testRunner() throws Exception {

        ATDRunner parallelThread = new ATDRunner();
        List<String> test = new ArrayList<>();
        test.add("ShareTests");
        boolean runner = parallelThread.runner("tests.loggedInUser", test);
        System.out.println(runner);

    }
}`
what should I do next?
and have error when try to run tests with command
`mvn clean -Dtest=Runner -DPlatform=android test`

error: java.lang.ClassCastException: class java.lang.String cannot be cast to class org.json.JSONObject (java.lang.String is in module java.base of loader 'bootstrap'; org.json.JSONObject is in unnamed module of loader 'app')
        at com.appium.capabilities.Capabilities.processJSONArrayItem(Capabilities.java:152)
        at com.appium.capabilities.Capabilities.processJSONArray(Capabilities.java:138)
        at com.appium.capabilities.Capabilities.lambda$loadAndOverrideFromEnvVars$2(Capabilities.java:103)

have you any advices or smth?
And thanks for future answers, and for your work to make life AQA easier.

**Comment by hungdao-testing** [comment]
Any update on how to setup distribution .  I triggered the Runner class, the log shows error. 

// At this time: my test class is empty methods, just to see what will happen once launching the Runner
```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'computer.local', ip: 'fe80:0:0:0:10bb:2c6d:a479:7d86%en0'
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.5', java.version: '17.0.14'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[Capabilities {app: /Users/progra..., automationName: XCUITest, clearSystemFiles: true, deviceName: iPhone 15 Pro, maxTypingFrequency: 10, platformName: IOS, preventWDAAttachments: true, shouldUseSingletonTestManager: false, simpleIsVisibleCheck: true, usePrebuiltWDA: true, wdaConnectionTimeout: 80000, wdaLaunchTimeout: 80000}]}]
Capabilities {app: /Users/progra..., automationName: XCUITest, clearSystemFiles: true, deviceName: iPhone 15 Pro, maxTypingFrequency: 10, platformName: IOS, preventWDAAttachments: true, shouldUseSingletonTestManager: false, simpleIsVisibleCheck: true, usePrebuiltWDA: true, wdaConnectionTimeout: 80000, wdaLaunchTimeout: 80000}
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:313)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:113)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:101)
	at com.appium.manager.AppiumDriverManager.createAppiumDriver(AppiumDriverManager.java:62)
	at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:52)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:104)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:89)
	at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:101)
	at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:74)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:55)
	at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:82)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:370)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```


Here is mine

capibilities.json
```ts
{
  "android": {
    "platformName": "android",
    "platformVersion": "7.0",
    "app": "./apps/formscli_android.apk",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {},
  "ios": {
    "platformName": "ios",
    "deviceName": "iPhone 15 Pro",
    "app": {
      "simulator": "./apps/formscli_ios.zip"
    },
    "automationName": "XCUITest",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "usePrebuiltWDA": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 15 Pro",
          "OS": "17.5"
        }
      ]
    }
  ],
  "serverConfig": {
    "server": {

      "use-plugins": [
        "device-farm"
      ],
      "plugin": {
        "device-farm": {
          "platform": "ios"
        }
      }
    }
  },
  "basePath": "/"
}
```

Next Question:
I have not sure which steps should be configured in the test class to connect ATD to appium, any up-to-date example
@saikrishna321
