### ISSUE TITLE
Cannot invoke "com.appium.capabilities.DriverSession.getUdid()" because the return value of "com.appium.manager.AppiumDeviceManager.getAppiumDevice()" is null

### ISSUE THREAD

**Issue by JeevaTamil** [AppiumTestDistribution/AppiumTestDistribution#1028]
I can invoke the drivers. But after invoking, I'm getting this error! Please help me!

Thanks in advance.

`
FAILED CONFIGURATION: @BeforeMethod setup
java.lang.NullPointerException: Cannot invoke "com.appium.capabilities.DriverSession.getUdid()" because the return value of "com.appium.manager.AppiumDeviceManager.getAppiumDevice()" is null
        at com.appium.manager.AppiumParallelTestListener.beforeInvocation(AppiumParallelTestListener.java:65)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:55)
        at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:67)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:354)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
        at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:589)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:808)
        at org.testng.TestRunner.run(TestRunner.java:603)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by saikrishna321** [comment]
@JeevaTamil Can you please provide full logs.

**Comment by JeevaTamil** [comment]
In Appium Logs, `2023-05-03 10:28:28:939 uncaughtException: write EPIPE` exception is displaying. Attached the full logs below.

[appium_logs.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/11381612/appium_logs.txt)

**Comment by saikrishna321** [comment]
@JeevaTamil Can you please try with latest version 

```
        <dependency>
            <groupId>com.github.AppiumTestDistribution</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>88b13db733</version>
        </dependency>
```

**Comment by saikrishna321** [comment]
Try version 13.0.0

**Comment by JeevaTamil** [comment]
Tried with 13.0.0.  This time I'm getting below error,
`java.lang.NullPointerException: Cannot invoke "io.appium.java_client.AppiumDriver.findElement(org.openqa.selenium.By)" because "this.driver" is null
`
I'm not sure where I'm missing!

[testLog.log](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/11544116/testLog.log)
[appium_logs.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/11544137/appium_logs.txt)

**Config.properties**
```
RUNNER=parallel
#APPIUM_JS_PATH=/home/linuxbrew/.linuxbrew/lib/node_modules/appium/index.js
CAPS=./caps/capabilities.json
FRAMEWORK=testng
SUITE_NAME=testApp
CATEGORY=sanity
RUNNER_LEVEL=methods
#LISTENERS=com.epam.reportportal.testng.ReportPortalTestNGListener
```
**Capabilities.json**
```
{
  "android": {
    "platformName": "android",
    "automationName": "UiAutomator2",
    "uiautomator2ServerInstallTimeout": 120000,
    "adbExecTimeout": 140000,
    "appPackage": "com.zoho.accounts.oneauth",
    "appActivity": "com.zoho.accounts.oneauth.v2.ui.login.WalkthroughActivity",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "usePrebuiltWDA": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "serverConfig" : {
    "server": {
      "use-plugins": ["device-farm", "appium-dashboard", "element-wait"],
      "plugin": {
        "device-farm": {
          "platform": "android"
        }
      }
    }
  }
}

```


Note: There is no line in the ADB logs.
