### ISSUE TITLE
Null Pointer Exception [Cucumber tests]

### ISSUE THREAD

**Issue by SudhanvaManjunath** [AppiumTestDistribution/AppiumTestDistribution#1029]
Hey @saikrishna321 , 

Was planning to use ATD with appium 2.0 and was facing below issue. Couldn't identify the root cause, would be really grateful, if you can help me understand what I am missing.

Please let me know if you need any additional details.

Caps:

`{
  "android":{
    "platformName":"android",
    "automationName":"UiAutomator2",
    "uiautomator2ServerInstallTimeout":120000,
    "adbExecTimeout":140000,
    "appPackage":"some package",
    "appActivity":"some activity",
    "app": {
      "local": "../Dummy.apk"
    },
    "noSign":true
  },
  "iOS":{
    "platformName":"iOS",
    "app":"./apps/Runner.zip",
    "deviceName":"iPhone",
    "wdaLaunchTimeout":80000,
    "wdaConnectionTimeout":80000,
    "preventWDAAttachments":true,
    "usePrebuiltWDA":true,
    "clearSystemFiles":true,
    "shouldUseSingletonTestManager":false,
    "simpleIsVisibleCheck":true,
    "maxTypingFrequency":10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "/Users/sxxx/.npm-global/lib/node_modules/appium/build/lib/main.js"
    }
  ],
  "serverConfig" : {
    "server": {
      "plugin": {
        "device-farm": {
          "platform": "both",
          "skipChromeDownload": true
        }
      }
    }
  }
}
`

`Platform=android` mvn clean -Dtest=RunCukes test
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.deliveryhero:Parallel-Appium:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.appium:java-client:jar -> duplicate declaration of version 8.3.0 @ line 83, column 21
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------< org.deliveryhero:Parallel-Appium >------------------
[INFO] Building Parallel-Appium 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Parallel-Appium ---
[INFO] Deleting /Users/s.manjunath/Documents/Project/Parallel/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Parallel-Appium ---
[WARNING] Using platform encoding (US-ASCII actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Parallel-Appium ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Parallel-Appium ---
[WARNING] Using platform encoding (US-ASCII actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Parallel-Appium ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /Users/s.manjunath/Documents/Project/Parallel/target/test-classes
[WARNING] /Users/s.manjunath/Documents/Project/Parallel/src/test/java/helpers/StepHelper.java: /Users/s.manjunath/Documents/Project/Parallel/src/test/java/helpers/StepHelper.java uses unchecked or unsafe operations.
[WARNING] /Users/s.manjunath/Documents/Project/Parallel/src/test/java/helpers/StepHelper.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0:test (default-test) @ Parallel-Appium ---
[INFO] Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running test.RunCukes
ThreadID: 1: RunCucumberTest
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
CucumberScenarioReporterListener
May 01, 2023 12:15:41 AM com.appium.utils.ConfigFileManager <clinit>
INFO: Using config file from [./configs/config.properties]
May 01, 2023 12:15:41 AM com.appium.capabilities.Capabilities validateRemoteHosts
INFO: ATD is Running on 127.0.0.1
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Found Chrome version - '112' on - '995AY18W6W'
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Found Chrome version - '95' on - '995AY18W6W'
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getPathForChromeDriver
INFO: ChromeDriver for Chrome version 112 on device: 995AY18W6W/Users/s.manjunath/.cache/selenium/chromedriver/mac64/112.0.5615.49/chromedriver
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Found Chrome version - '112' on - 'ef770771'
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Found Chrome version - '62' on - 'ef770771'
May 01, 2023 12:15:44 AM com.appium.device.HostMachineDeviceManager getPathForChromeDriver
INFO: ChromeDriver for Chrome version 112 on device: ef770771/Users/s.manjunath/.cache/selenium/chromedriver/mac64/112.0.5615.49/chromedriver
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener <init>
INFO: ThreadID: 1: CucumberScenarioListener

May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener runStartedHandler
INFO: runStartedHandler
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener runStartedHandler
INFO: ThreadID: 1: beforeSuite: 

May 01, 2023 12:15:44 AM com.appium.manager.LocalAppiumManager startAppiumServer
INFO: LocalAppiumManagerStarting Appium Server on Localhost
Picking UserSpecified Path for AppiumServiceBuilder
java.lang.NullPointerException
        at io.appium.java_client.service.local.AppiumDriverLocalService.destroyProcess(AppiumDriverLocalService.java:220)
        at io.appium.java_client.service.local.AppiumDriverLocalService.destroyProcess(AppiumDriverLocalService.java:253)
        at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:176)
        at com.appium.manager.LocalAppiumManager.startAppiumServer(LocalAppiumManager.java:72)
        at com.appium.manager.AppiumServerManager.startAppiumServerSingleSession(AppiumServerManager.java:31)
        at com.appium.manager.AppiumServerManager.startAppiumServer(AppiumServerManager.java:49)
        at com.cucumber.listener.CucumberScenarioListener.runStartedHandler(CucumberScenarioListener.java:86)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunStarted(CucumberExecutionContext.java:64)
        at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:52)
        at io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:108)
        at io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
        at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
ThreadID: 1: in overridden scenarios
[[Ljava.lang.Object;@4e31c3ec
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener caseStartedHandler
INFO: caseStartedHandler: As user i should be able to login in with valid credentials
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener caseStartedHandler
INFO: ThreadID: 25: beforeScenario: for scenario: As user i should be able to login in with valid credentials

May 01, 2023 12:15:44 AM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@552279ae for Execution
May 01, 2023 12:15:44 AM com.appium.manager.AppiumDriverManager initialiseDriver
INFO: Capabilities: Capabilities {adbExecTimeout: 140000, app: /Users/s.manjunath/Document..., appActivity: com.deliveryhero.vpm.dh_vt_..., appPackage: com.deliveryhero.pandaporta..., automationName: UiAutomator2, chromedriverExecutable: /Users/s.manjunath/.cache/s..., chromedriverPort: 63102, deviceName: android, noSign: true, platformName: ANDROID, systemPort: 63094, udid: 995AY18W6W, uiautomator2ServerInstallTimeout: 120000}
java.lang.NullPointerException
        at com.appium.manager.LocalAppiumManager.getAppiumUrl(LocalAppiumManager.java:40)
        at com.appium.manager.LocalAppiumManager.getRemoteWDHubIP(LocalAppiumManager.java:55)
        at com.appium.manager.AppiumDriverManager.getRemoteWDHubIP(AppiumDriverManager.java:109)
        at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:51)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:116)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:122)
        at com.cucumber.listener.CucumberScenarioListener.allocateDeviceAndStartDriver(CucumberScenarioListener.java:62)
        at com.cucumber.listener.CucumberScenarioListener.caseStartedHandler(CucumberScenarioListener.java:99)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:66)
        at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:228)
        at io.cucumber.core.runner.TestCase.run(TestCase.java:92)
        at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
        at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$0(TestNGCucumberRunner.java:116)
        at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
        at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:113)
        at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener runFinishedHandler
INFO: runFinishedHandler: Result{status=FAILED, duration=0, error=io.cucumber.core.exception.CucumberException: java.lang.RuntimeException: java.lang.NullPointerException}
May 01, 2023 12:15:44 AM com.cucumber.listener.CucumberScenarioListener runFinishedHandler
INFO: ThreadID: 1: afterSuite: 

java.lang.NullPointerException
        at com.appium.manager.LocalAppiumManager.destroyAppiumNode(LocalAppiumManager.java:46)
        at com.appium.manager.AppiumServerManager.stopAppiumServer(AppiumServerManager.java:56)
        at com.cucumber.listener.CucumberScenarioListener.runFinishedHandler(CucumberScenarioListener.java:167)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:93)
        at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)
        at io.cucumber.testng.TestNGCucumberRunner.finish(TestNGCucumberRunner.java:126)
        at io.cucumber.testng.AbstractTestNGCucumberTests.tearDownClass(AbstractTestNGCucumberTests.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
        at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
?????????????????????????????????????????????????????????????????????????????????????
? Share your Cucumber Report with your team at https://reports.cucumber.io          ?
? Activate publishing with one of the following:                                    ?
?                                                                                   ?
? src/test/resources/cucumber.properties:          cucumber.publish.enabled=true    ?
? src/test/resources/junit-platform.properties:    cucumber.publish.enabled=true    ?
? Environment variable:                            CUCUMBER_PUBLISH_ENABLED=true    ?
? JUnit:                                           @CucumberOptions(publish = true) ?
?                                                                                   ?
? More information at https://reports.cucumber.io/docs/cucumber-jvm                 ?
?                                                                                   ?
? Disable this message with one of the following:                                   ?
?                                                                                   ?
? src/test/resources/cucumber.properties:          cucumber.publish.quiet=true      ?
? src/test/resources/junit-platform.properties:    cucumber.publish.quiet=true      ?
?????????????????????????????????????????????????????????????????????????????????????
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.94 s <<< FAILURE! - in test.RunCukes
[ERROR] test.RunCukes.runScenario["As user i should be able to login in with valid credentials", "Optional[Login Test]"](1)  Time elapsed: 0.127 s  <<< FAILURE!
java.lang.RuntimeException: java.lang.NullPointerException
        at com.cucumber.listener.CucumberScenarioListener.allocateDeviceAndStartDriver(CucumberScenarioListener.java:66)
        at com.cucumber.listener.CucumberScenarioListener.caseStartedHandler(CucumberScenarioListener.java:99)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:66)
        at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:228)
        at io.cucumber.core.runner.TestCase.run(TestCase.java:92)
        at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
        at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$0(TestNGCucumberRunner.java:116)
        at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
        at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:113)
        at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:31)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
        at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at com.appium.manager.LocalAppiumManager.getAppiumUrl(LocalAppiumManager.java:40)
        at com.appium.manager.LocalAppiumManager.getRemoteWDHubIP(LocalAppiumManager.java:55)
        at com.appium.manager.AppiumDriverManager.getRemoteWDHubIP(AppiumDriverManager.java:109)
        at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:51)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:116)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:122)
        at com.cucumber.listener.CucumberScenarioListener.allocateDeviceAndStartDriver(CucumberScenarioListener.java:62)
        ... 27 more

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   RunCukes>AbstractTestNGCucumberTests.runScenario:31 ? Runtime java.lang.NullPointerException
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.870 s
[INFO] Finished at: 2023-05-01T00:15:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project Parallel-Appium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/s.manjunath/Documents/Project/Parallel/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
`

**Comment by SudhanvaManjunath** [comment]
Nvm, The issue was with java client and selenium version., reduced the selenium version to <4.8.2, it works fine!
