### ISSUE TITLE
Appium server not getting started locally for IOS

### ISSUE THREAD

**Issue by LavanyaJK** [AppiumTestDistribution/AppiumTestDistribution#1042]
@anandbagmar @saikrishna321 
I am facing issue while running IOS testcase on local,
have installed appium, plugins and drivers locally in the AppiumTestDistribution directory using below commands,
#npm install appium
#npm install appium-uiautomator2-driver
#npm install appium-device-farm
#npm install go-ios

Android runs are working perfectly fine. 

For IOS, the simulator(booted) is found, and able to get the device from device-farm, but appium server is not starting in the local,
Please find the logs below,

[INFO] Running com.test.site.Runner
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
 INFO [main] (ConfigFileManager.java:35)- Using config file from [./configs/iOSConfig.properties]
 INFO [main] (AppiumServerManager.java:51)- com.appium.manager.AppiumServerManagerStarting Appium Server on Localhost
 35m[Adirectoryppium],  ls    tat.java:101)- Picking UserSpecified Path for AppiumServiceBuilder
at Object.lstatSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/graceful-fs/polyfills.js:318:34)
[debug] [Appium]     at statFunc (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:24:20)
[debug] [Appium]     at getStatsSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:25:19)
[debug] [Appium]     at Object.checkPathsSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:67:33)
[debug] [Appium]     at Object.copySync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
[debug] [Appium]     at derivedPathExtracted (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:99:36)
[debug] [Appium]     at IOSDeviceManager.derivedDataPath (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:117:17)
[debug] [Appium]     at IOSDeviceManager.<anonymous> (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:225:307)
[debug] [Appium]     at Generator.next (<anonymous>)t' ] }
[debug] [Appium]     at fulfilled (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:5:58)
[debug] [Appium]     at processTicksAndRejections (node:internal/process/task_queues:95:5)Distribution/node_modules/appium-xcuitest-driver
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 60.689 s <<< FAILURE! - in com.test.site.Runner
[ERROR] testApp(com.test.site.Runner)  Time elapsed: 60.403 s  <<< FAILURE!etup/AppiumTestDistribution/node_modules/appium-uiautomator2-driver
io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: device-farm
[The local appium server has not been started, Reason: Timed out waiting for [http://127.0.0.1:3639/wd/hub/status] to be available after 60006 ms, Consider increasing the server startup timeout value (currently 60000ms), Node.js executable path: /opt/homebrew/bin/node, Arguments: [/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium/build/lib/main.js, --port, 3639, --address, 127.0.0.1, --log, /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/target/appiumlogs/appium_logs.txt, --base-path, /wd/hub/, --relaxed-security, --config, /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/target/server.json], Output: [Appium] Attempting to load plugin device-farm...NT: no such fie:fs:1593:3)
[debug] [Appi5m[Apirectory,pium] m  st   aatlavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm
t Object.lstatSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/graceful-fs/polyfills.js:318:34)
[debug] [Appium]     at statFunc (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:24:20)
[debug] [Appium]     at getStatsSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:25:19)
[debug] [Appium]     at Object.checkPathsSync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/util/stat.js:67:33)
[debug] [Appium]     at Object.copySync (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
[debug] [Appium]     at derivedPathExtracted (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:99:36)
[debug] [Appium]     at IOSDeviceManager.derivedDataPath (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:117:17)
[debug] [Appium]     at IOSDeviceManager.<anonymous> (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:225:307)
[debug] [Appium]     at Generator.next (<anonymous>)jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-xcuitest-driver
[debug] [Appium]     at fulfilled (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-managers/IOSDeviceManager.js:5:58)
[debug] [Appium]     at processTicksAndRejections (node:internal/process/task_queues:95:5)Distribution/node_modules/appium-uiautomator2-driver
]device-farm] ???????????? Device Farm Plugin will be served at ???? http://localhost:3639/device-farm
[device-at com.test.site.Runner.testApp(Runner.java:27)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:3639/wd/hub/status] to be available after 60006 ms
[Appium]at com.test.site.Runner.testApp(Runner.java:27)p[35osm[Appium]ible tm Errhat a driver or plor: Eugin tNOENT: no such file or directory, lstat
Caused by: java.util.concurrent.TimeoutException to update the server and failed. Original error:de ENOENT: no such fil:fs:1593:3)
[dee orbat com.test.site.Runner.testApp(Runner.java:27)

Please provide the solution, and thank you in advance.

**Comment by saikrishna321** [comment]
@LavanyaJK I'm unable to reproduce the issue 

https://gist.github.com/saikrishna321/4563c0f70078a8c74f15200dd4883e61

Capabilities are as

```
{
  "iOS": {
    "platformName": "iOS",
    "app": "./apps/VodQAReactNative.zip",
    "deviceName": "iPhone",
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10,
    "automationName": "XCUITest",
    "usePrebuiltWDA": true,
    "appium:iPhoneOnly": true
  },
  "serverConfig" : {
    "server": {
      "use-plugins": ["device-farm", "element-wait"],
      "plugin": {
        "device-farm": {
          "platform": "iOS",
          "skipChromeDownload": true
        }
      }
    }
  },
  "appiumServerPath": "./node_modules/appium/build/lib/main.js"
}



```

server.json 

```
{
  "server": {
    "plugin": {
      "device-farm": {
        "skipChromeDownload": true,
        "platform": "both"
      }
    },
    "port": 31337,
    "use-plugins": ["device-farm"]
  }
}

```

**Comment by saikrishna321** [comment]
@LavanyaJK Does your test work on Browserstack outside ATD?

**Comment by LavanyaJK** [comment]
Hi @saikrishna321,

Yes, I have executed testcases on BrowserStack outside ATD, but only worked on Android, not on IOS,

I just checked android case on browserstack, it executed successfully,
<img width="1428" alt="image" src="https://github.com/AppiumTestDistribution/AppiumTestDistribution/assets/104868123/0e2a9991-d838-4c86-96b5-e653b6c549f8">



But for iOS, below error message appears,

[debug] [AppiumDriver@0346] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"appium:app":"bs://4e4e5743713d29a3599946e9949979cf9e20375f","appium:automationName":"XCUITest","appium:browserstack.appium_version":"2.0.0","appium:browserstack.debug":true,"appium:clearSystemFiles":true,"appium:deviceName":"iPhone","appium:maxTypingFrequency":10,"appium:preventWDAAttachments":true,"appium:shouldUseSingletonTestManager":false,"appium:simpleIsVisibleCheck":true,"appium:wdaConnectionTimeout":80000,"appium:wdaLaunchTimeout":80000,"platformName":"IOS"}}]
[AppiumDriver@0346] Plugins which can handle cmd 'createSession': device-farm
[AppiumDriver@0346] Plugin device-farm is now handling cmd 'createSession'
{
  'appium:app': 'bs://4e4e5743713d29a3599946e9949979cf9e20375f',
  'appium:automationName': 'XCUITest',
  'appium:browserstack.appium_version': '2.0.0',
  'appium:browserstack.debug': true,
  'appium:clearSystemFiles': true,
  'appium:deviceName': 'iPhone',
  'appium:maxTypingFrequency': 10,
  'appium:preventWDAAttachments': true,
  'appium:shouldUseSingletonTestManager': false,
  'appium:simpleIsVisibleCheck': true,
  'appium:wdaConnectionTimeout': 80000,
  'appium:wdaLaunchTimeout': 80000,
  platformName: 'IOS'
}
[device-farm] {"platform":"ios","name":"","deviceType":"real","busy":false,"userBlocked":false}
[device-farm] Waiting for free device
[device-farm] 📱 Device found: {"os_version":"15","deviceName":"iPhone 11 Pro","platform":"ios","host":"http://hub-cloud.browserstack.com","busy":false,"userBlocked":false,"deviceType":"real","capability":{"os_version":"15","deviceName":"iPhone 11 Pro","platform":"ios"},"cloud":"browserstack","name":"iPhone 11 Pro","sdk":"15","udid":"iPhone 11 Pro","offline":false,"meta":{"revision":0,"created":1689183697258,"version":0},"$loki":1}
[device-farm] 📱 Blocking device iPhone 11 Pro for new session
[device-farm] Updating cloud Capability for Device
[device-farm] Remote Host URL - https://lavanyajk_eLORhQ:ZUQCK3vxTNcbN7eNPzqm@hub-cloud.browserstack.com/wd/hub/session
[device-farm] Creating cloud session
No tvOS simulators found!
uncaughtException: Cannot destructure property 'state' of 'allDevices.find(...)' as it is undefined.
TypeError: Cannot destructure property 'state' of 'allDevices.find(...)' as it is undefined.
    at /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/data-service/device-service.js:45:21
    at Array.forEach (<anonymous>)
    at setSimulatorState (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/data-service/device-service.js:42:13)
    at /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-utils.js:276:58
    at Generator.next (<anonymous>)
    at fulfilled (/Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/node_modules/appium-device-farm/lib/device-utils.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'LM0003404', ip: '2409:408c:8d85:62c:d81e:c00e:d884:2223%en0'
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:549)
        at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
        at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:104)
        at com.appium.manager.AppiumDriverManager.createAppiumDriver(AppiumDriverManager.java:56)
        at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:46)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:98)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:83)
        at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:101)
        at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:74)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:55)
        at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:67)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:641)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.3', java.version: '11.0.19'
Driver info: driver.version: IOSDriver
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:137)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
        at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
        ... 23 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
        ... 27 more
Caused by: java.io.UncheckedIOException: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:73)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at io.appium.java_client.remote.AppiumCommandExecutor.lambda$null$0(AppiumCommandExecutor.java:187)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
        at org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
        at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
        at io.appium.java_client.remote.AppiumCommandExecutor.lambda$null$0(AppiumCommandExecutor.java:187)
        at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
        at org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
        ... 32 more
Caused by: org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
        at org.asynchttpclient.exception.RemotelyClosedException.INSTANCE(Unknown Source)
 INFO [TestNG-test=ATDTest-1] (AppiumParallelMethodTestListener.java:122)- Driver Session exisstsfalsenull
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:25)- SessionContext default constructor
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:51)- Using reportportal.properties file from src/test/resources/reportportal.properties
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:57)- Loaded reportportal.properties file - /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/src/test/resources/reportportal.properties
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:29)- Initialized SessionContext
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:42)- Removing context for thread - 27
com.appium.executor.CustomeListener.afterInvocation() was invoked
FAILED: dragNDrop
java.lang.IllegalArgumentException: Input must be set
        at org.openqa.selenium.internal.Require.nonNull(Require.java:60)
        at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:94)
        at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:74)
        at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:43)
        at com.test.site.UserBaseTest.waitForElement(UserBaseTest.java:26)
        at com.test.site.UserBaseTest.login(UserBaseTest.java:22)
        at com.test.site.SliderTest.dragNDrop(SliderTest.java:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
<img width="1418" alt="image" src="https://github.com/AppiumTestDistribution/AppiumTestDistribution/assets/104868123/209a61db-c4fa-48aa-86cd-78ab0a335bda">

### **Please find the Browserstack appium logs -**
[Appium logs.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/12030897/Appium.logs.txt)

**the .ipa app launches on browserstack successfully, but test case fails due to above mentioned exception.**

Do you have an idea on this issue or how to resolve this.
Thank you.

**Comment by saikrishna321** [comment]
@LavanyaJK Can you add `iosDeviceType=real` to the server config 

```
{
  "android": {
    "automationName": "UIAutomator2",
    "app": "bs://6b27ca8387cbd29e429f5fea9595edf8460eff60",
    "noSign": true,
    "browserstack.appium_version": "2.0.0",
    "project": "First TestNg Android Project",
    "build": "browserstack-1111",
    "name": "first_test",
    "browserstack.debug": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": "bs://4e4e5743713d29a3599946e9949979cf9e20375f",
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "serverConfig" : {
    "server": {
      "use-plugins": ["device-farm"],
      "plugin": {
        "device-farm": {
          "platform": "iOS",
          "skipChromeDownload": true,
          "iosDeviceType": "real",
          "cloud":
            {
              "cloudName": "browserstack",
              "url": "http://hub-cloud.browserstack.com",
              "devices": [
                {
                  "deviceName": "Samsung Galaxy S22",
                  "os_version": "12.0",
                  "platform": "android"
                },
                {
                  "deviceName": "iPhone 11 Pro",
                  "os_version": "15",
                  "platform": "ios"
                }
              ]
            }
        }
      }
    }
  },
  "appiumServerPath": "./node_modules/appium/build/lib/main.js"
}

```
