### ISSUE TITLE
iOS execution not working on pCloudy 

### ISSUE THREAD

**Issue by LavanyaJK** [AppiumTestDistribution/AppiumTestDistribution#1043]
Hi @saikrishna321,

We tried executing the IOS test case on pCloudy with the below capabilities on ATD, but "org.openqa.selenium.SessionNotCreatedException" exception is thrown,

{
  "iOS": {
    "app": "AJIO_test_9_8_29.ipa",
    "newCommandTimeout": 600,
    "launchTimeout": 90000,
    "platformName": "ios",
    "os_version": "15",
    "device": "Apple",
    "acceptAlerts": true,
    "automationName": "XCUITest",
    "bundleId": "com.ril.ajiofnl",
    "autoGrantPermissions": true,
    "pCloudy_DeviceFullName": "APPLE_iPhone11ProMax_ios_15.0.0_b99a8",
    "pCloudy_DurationInMinutes": 10,
    "pCloudy_WildNet": "false",
    "pCloudy_EnableVideo": "true",
    "pCloudy_EnablePerformanceData": "true",
    "pCloudy_EnableDeviceLogs": "true",
    "unicodeKeyboard": true,
    "resetKeyboard": true,
    "noReset": false,
    "appiumVersion": "2.0.0"
  },
  "serverConfig": {
    "server": {
      "use-plugins": ["device-farm"],
      "port": 31337,
      "plugin": {
        "device-farm": {
          "platform": "iOS",
          "skipChromeDownload": true,
          "iosDeviceType": "real",
          "cloud":
            {
              "cloudName": "pCloudy",
              "url": "https://device.pcloudy.com/appiumcloud/wd/hub",
              "devices": [
                {
                  "pCloudy_DeviceManufacturer": "APPLE",
                  "pCloudy_DeviceVersion": "15.0.0",
                  "platform": "ios"
                }
              ]
            }
        }
      }
    }
  },
  "appiumServerPath": "/opt/homebrew/lib/node_modules/appium/build/lib/main.js"
}

The session gets created and device will be assigned, but testcase execution is not working.
<img width="1522" alt="image" src="https://github.com/AppiumTestDistribution/AppiumTestDistribution/assets/104868123/786d63dc-9249-4050-9ebc-6edcb4b55352">

### **Below error message appears -**
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: java.net.SocketTimeoutException : Read timed out, Please check the remote appium server log to know the reason for failure 
Host info: host: 'LM0003404', ip: 'fe80:0:0:0:437:9e2a:c247:6a91%en0'
Build info: version: '4.10.0', revision: 'c14d967899'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6.3', java.version: '11.0.19'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[{appium:acceptAlerts=true, appium:app=AJIO_test_9_8_29.ipa, appium:appiumVersion=2.0.0, appium:autoGrantPermissions=true, appium:automationName=XCUITest, appium:bundleId=com.ril.ajiofnl, appium:device=Apple, appium:launchTimeout=90000, appium:newCommandTimeout=600, appium:noReset=false, appium:os_version=15, appium:pCloudy_DurationInMinutes=10, appium:pCloudy_EnableDeviceLogs=true, appium:pCloudy_EnablePerformanceData=true, appium:pCloudy_EnableVideo=true, appium:pCloudy_WildNet=false, platformName=IOS, appium:resetKeyboard=true, appium:unicodeKeyboard=true}], desiredCapabilities=Capabilities {acceptAlerts: true, app: AJIO_test_9_8_29.ipa, appiumVersion: 2.0.0, autoGrantPermissions: true, automationName: XCUITest, bundleId: com.ril.ajiofnl, device: Apple, launchTimeout: 90000, newCommandTimeout: 600, noReset: false, os_version: 15, pCloudy_DurationInMinutes: 10, pCloudy_EnableDeviceLogs: true, pCloudy_EnablePerformanceData: true, pCloudy_EnableVideo: true, pCloudy_WildNet: false, platformName: IOS, resetKeyboard: true, unicodeKeyboard: true}}]
Capabilities {acceptAlerts: true, app: AJIO_test_9_8_29.ipa, appiumVersion: 2.0.0, autoGrantPermissions: true, automationName: XCUITest, bundleId: com.ril.ajiofnl, device: Apple, launchTimeout: 90000, newCommandTimeout: 600, noReset: false, os_version: 15, pCloudy_DurationInMinutes: 10, pCloudy_EnableDeviceLogs: true, pCloudy_EnablePerformanceData: true, pCloudy_EnableVideo: true, pCloudy_WildNet: false, platformName: IOS, resetKeyboard: true, unicodeKeyboard: true}
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
        at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
        at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
        at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:104)
        at com.appium.manager.AppiumDriverManager.createAppiumDriver(AppiumDriverManager.java:56)
        at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:46)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:98)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:83)
        at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:101)
        at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:74)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:55)
        at org.testng.internal.invokers.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:67)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:641)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
 INFO [TestNG-test=ATDTest-1] (AppiumParallelMethodTestListener.java:122)- Driver Session exisstsfalsenull
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:25)- SessionContext default constructor
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:51)- Using reportportal.properties file from src/test/resources/reportportal.properties
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:57)- Loaded reportportal.properties file - /Users/lavanya.jk/IdeaProjects/QECC_Meetup/AppiumTestDistribution/src/test/resources/reportportal.properties
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:29)- Initialized SessionContext
 INFO [TestNG-test=ATDTest-1] (SessionContext.java:42)- Removing context for thread - 27
com.appium.executor.CustomeListener.afterInvocation() was invoked
FAILED: dragNDrop
java.lang.IllegalArgumentException: Input must be set
        at org.openqa.selenium.internal.Require.nonNull(Require.java:60)
        at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:94)
        at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:74)
        at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:43)
        at com.test.site.UserBaseTest.waitForElement(UserBaseTest.java:26)
        at com.test.site.UserBaseTest.login(UserBaseTest.java:22)
        at com.test.site.SliderTest.dragNDrop(SliderTest.java:12)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Command used to run testcase** -  Platform='iOS' CLOUD_KEY=<cloud_key> CLOUD_USERNAME=<cloud
-username> CONFIG_FILE='./configs/pcloudy_config.properties' mvn clean -Dtest=Runner test -Dcheckstyle.skip
 
**Please find the both teswiz and ATD full logs of the above issue -** 
[ATD_pCloudy_logs.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/12081595/ATD_pCloudy_logs.txt)
[Teswiz_pCloudy_logs.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/12081597/Teswiz_pCloudy_logs.txt)

cc: @anandbagmar

**Comment by saikrishna321** [comment]
@LavanyaJK Please attach logs as gist its easy to read. Looking at the error i'm thinking pCloudy is taking more time to respond back to the request. May be we should increase the connection timeout. 

can you change the timeout here https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/main/src/main/java/com/appium/manager/AppiumServerManager.java#L60 and build local and check if it helps.

**Comment by saikrishna321** [comment]
closing as no response.
