### ISSUE TITLE
Appium driver always null when run in parallel mode

### ISSUE THREAD

**Issue by akbrkml** [AppiumTestDistribution/AppiumTestDistribution#1078]
Hello mate @saikrishna321, I'm just trying to run parallel test using sample [project](https://github.com/saikrishna321/PageObjectPatternAppium) and got this error (the driver always null). 

I'm using the latest version.

But, when using distribute mode, totally fine.

Here is the log. 

`java.lang.NullPointerException: Cannot invoke "io.appium.java_client.AppiumDriver.getCapabilities()" because "driver" is null
        at com.appium.pages.LoginPage.<init>(LoginPage.java:25)
        at com.appium.tests.LoginTest.setUp(LoginTest.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
        at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
        at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:803)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:589)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:808)
        at org.testng.TestRunner.run(TestRunner.java:603)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
        at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)`

Thank you.

**Comment by saikrishna321** [comment]
@akbrkml Can you try with the below version 

```
	<dependency>
	    <groupId>com.github.AppiumTestDistribution</groupId>
	    <artifactId>AppiumTestDistribution</artifactId>
	    <version> a1482f15da </version>
	</dependency>
```

**Comment by akbrkml** [comment]
@saikrishna321 still error `Could not find artifact io.cucumber:messages:pom:19.1.4-SNAPSHOT in [jitpack.io](http://jitpack.io/) (https://jitpack.io/)`

**Comment by saikrishna321** [comment]
Please check your network. I'm unable to reproduce this issue.

**Comment by akbrkml** [comment]
Great, it works well. Thanks
