### ISSUE TITLE
AppiumServerManager using  withTimeout of AppiumServiceBuilder, which does not exists

### ISSUE THREAD

**Issue by AnilPatidar** [AppiumTestDistribution/AppiumTestDistribution#1080]
@saikrishna321  **ATD : atdVersion=13.1.3**

**Exception :** 
java.lang.NoSuchMethodError: 'org.openqa.selenium.remote.service.DriverService$Builder io.appium.java_client.service.local.AppiumServiceBuilder.withTimeout(java.time.Duration)'
	at com.appium.manager.AppiumServerManager.startAppiumServer(AppiumServerManager.java:64)
	at com.appium.manager.ATDRunner.<init>(ATDRunner.java:39)
	at com.games24x7.e2e.atdRunner.RunnerTest.testRunner(RunnerTest.java:88)
	

  **Code :** 
   public void startAppiumServer(String host) throws Exception {
        LOGGER.info(LOGGER.getName() + "Starting Appium Server on Localhost");
        new File(
                System.getProperty("user.dir")
                        + FileLocations.APPIUM_LOGS_DIRECTORY
                        + "appium_logs.txt").getParentFile().mkdirs();
        AppiumDriverLocalService appiumDriverLocalService;
        AppiumServiceBuilder builder =
                getAppiumServerBuilder(host)
                        .withLogFile(new File(
                                System.getProperty("user.dir")
                                        + FileLocations.APPIUM_LOGS_DIRECTORY
                                        + "appium_logs.txt"))
                        .withIPAddress(host)
                        .withTimeout(Duration.ofSeconds(60))
                        .withArgument(GeneralServerFlag.BASEPATH, "/wd/hub")
                        .withArgument(() -> "--config", System.getProperty("user.dir")
                                + FileLocations.SERVER_CONFIG)
                        .withArgument(GeneralServerFlag.RELAXED_SECURITY)
                        .usingAnyFreePort();
        appiumDriverLocalService = builder.build();
        appiumDriverLocalService.start();
        LOGGER.info(LOGGER.getName() + "Appium Server Started at......"
                + appiumDriverLocalService.getUrl());
        setAppiumDriverLocalService(appiumDriverLocalService);
    }

**Comment by AnilPatidar** [comment]
Yes, with some reason, gradle is not downloading the latest selenium version mentioned in appium java client. it is fixed now
