### ISSUE TITLE
Issue while executing tests with extentX logging

### ISSUE THREAD

**Issue by dkjha52** [AppiumTestDistribution/AppiumTestDistribution#150]
I am getting below error in log (This happens when test fail) while executing test with extentX logging - 
**************ClosingAppiumSession****************10
FAILED CONFIGURATION: @AfterMethod killServer([TestResult name=addComment on [AddCommentTest passed=0 failed=0 skipped=0] status=FAILURE method=AddCommentTest.addComment()[pri:0, instance:[AddCommentTest passed=0 failed=0 skipped=0]] output={null}])
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:27017/csrfToken
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:69)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:53)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:48)
	at com.aventstack.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:425)
	at com.aventstack.extentreports.Report.lambda$addScreenCapture$5(Report.java:79)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.addScreenCapture(Report.java:77)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:644)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:650)
	at com.appium.manager.AppiumParallelTest.endLogTestResults(AppiumParallelTest.java:465)
	at com.appium.config.UserBaseTest.killServer(UserBaseTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:27017/csrfToken
	at java.net.URI$Parser.fail(URI.java:2848)

**Comment by saikrishna321** [comment]
@dkjha52 i tried with latest extentX it works fine. command to run ExtentX="true" mvn clean -Dtest=Runner test

**Comment by dkjha52** [comment]
I have also used the same command and extentX works fine when no screen shot attached. But when test fails and generates screenshot then I am getting this issue. Please give some highlight so I can resolve this issue.

**Comment by dkjha52** [comment]
@saikrishna321 I got the solution. Actually ExtentManager.jave contains this code block - 
// server URL
        // ! must provide this to be able to upload snapshots
        String url = host + ":" + port;
        if (!url.isEmpty()) {
           extentx.config().setServerUrl(url);
        }

The port created the problem. This port value should not be the mongodb_port (27017). The above code should be look like this - 
// ! must provide this to be able to upload snapshots
        extentx.config().setServerUrl("http://localhost:1337");

**Comment by saikrishna321** [comment]
@dkjha52 thanks for looking into it ... does this get the screenshots on ExtentX ?

**Comment by dkjha52** [comment]
@saikrishna321 No, screenshots are still not showing on ExtentX. Will update you once I got success on this issue.

**Comment by dkjha52** [comment]
@saikrishna321 Yes I am getting the screenshot on ExtentX. Now you can close this issue.

**Comment by saikrishna321** [comment]
@dkjha52 would you want to raise a PR on the changes ? that would help

**Comment by dkjha52** [comment]
Yes. Please

**Comment by saikrishna321** [comment]
@dkjha52 will keep this open till you raise the PR

**Comment by saikrishna321** [comment]
@dkjha52 any updates on the PR?

**Comment by dkjha52** [comment]
@saikrishna321 I am not able to push the changes. Getting error - remote: Permission to saikrishna321/AppiumTestDistribution.git denied to dkjha52.

Once I get the permission then will created the PR.

**Comment by saikrishna321** [comment]
@dkjha52 you need to fork the repo and push your changes to your forked repo and create a PR from there

**Comment by dkjha52** [comment]
@saikrishna321 Created pull request.

**Comment by hemano** [comment]
I'm also facing the same issue. Until I don't do CI execution, can I make changes in the PR to the my fork?
https://github.com/saikrishna321/AppiumTestDistribution/pull/166

**Comment by saikrishna321** [comment]
@hemano if you send  a PR for this fix i can merge it .. @dkjha52 raised PR has conflicts

**Comment by hemano** [comment]
@saikrishna321 Raised a new PR.
https://github.com/saikrishna321/AppiumTestDistribution/pull/198
