### ISSUE TITLE
org.testng.TestNGException: java.net.URISyntaxException on Windows

### ISSUE THREAD

**Issue by carla-sarappa** [AppiumTestDistribution/AppiumTestDistribution#226]
Exception thrown when trying to use the project on a Windows machine.

What this is trying to do is get a pathname as a URI which is why it's failing in Windows.
The fix for this is to parse the pathname to be an actual URI with toURI(). 

```org.testng.TestNGException: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Tsuki\automation\kiwi/target/parallel.xml

	at org.testng.TestNG.parseSuite(TestNG.java:319)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:334)
	at org.testng.TestNG.initializeEverything(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1139)
	at com.appium.executor.MyTestExecutor.runMethodParallel(MyTestExecutor.java:150)
	at com.appium.manager.ParallelThread.parallelExecution(ParallelThread.java:164)
	at com.appium.manager.ParallelThread.triggerTest(ParallelThread.java:80)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:72)
	at com.appium.manager.ParallelThread.runner(ParallelThread.java:76)
```

**Comment by SrinivasanTarget** [comment]
Yes we are aware of it. please exclude testng and add it seperately. Or Fix is already there in master, where you can point to master and give a try.

**Comment by saikrishna321** [comment]
@carla-sarappa can you pls test it with version 7.0.1
