### ISSUE TITLE
Support for Java 8 lambda step definitions for Cucumber

### ISSUE THREAD

**Issue by 99heitor** [AppiumTestDistribution/AppiumTestDistribution#246]
Currently, it seems there's no way use the AppiumTestDistribution framework with lambda step definitions, as shown [here](https://cucumber.io/docs/reference/jvm#lambda-expressions-java-8).
I get the following exception when attempting to do so:

```FAILED: feature(Settings page)
        Runs Cucumber Feature
cucumber.runtime.CucumberException: Failed to instantiate class com.appium.steps.SettingsSteps
	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:46)
	at cucumber.runtime.java.DefaultJavaObjectFactory.getInstance(DefaultJavaObjectFactory.java:32)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:131)
	at cucumber.runtime.Runtime.buildBackendWorlds(Runtime.java:140)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:38)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.java.DefaultJavaObjectFactory.cacheNewInstance(DefaultJavaObjectFactory.java:40)
	... 27 more
Caused by: java.lang.AbstractMethodError: cucumber.runtime.java8.ConstantPoolTypeIntrospector.getGenericTypes(Ljava/lang/Class;)[Ljava/lang/reflect/Type;
	at cucumber.runtime.java.Java8StepDefinition.<init>(Java8StepDefinition.java:45)
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:162)
	at cucumber.api.java8.En.Given(En.java:190)
	at com.appium.steps.SettingsSteps.<init>(SettingsSteps.java:13)
	... 32 more

```

**Comment by saikrishna321** [comment]
@99heitor will look into this
