### ISSUE TITLE
After clone the project nothing is working - Can't run testng.xml

### ISSUE THREAD

**Issue by eyalpartner** [AppiumTestDistribution/AppiumTestDistribution#370]
"C:\Program Files\Java\jdk1.8.0_141\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6\lib\idea_rt.jar=58115:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6\plugins\testng\lib\testng-plugin.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\rt.jar;C:\Users\OSN20933\IdeaProjects\AppiumTestDistribution\target\test-classes;C:\Users\OSN20933\IdeaProjects\AppiumTestDistribution\target\classes;C:\Users\OSN20933\.m2\repository\io\appium\java-client\6.1.0\java-client-6.1.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-java\3.12.0\selenium-java-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-chrome-driver\3.12.0\selenium-chrome-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-edge-driver\3.12.0\selenium-edge-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-firefox-driver\3.12.0\selenium-firefox-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-ie-driver\3.12.0\selenium-ie-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-opera-driver\3.12.0\selenium-opera-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-remote-driver\3.12.0\selenium-remote-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-safari-driver\3.12.0\selenium-safari-driver-3.12.0.jar;C:\Users\OSN20933\.m2\repository\net\bytebuddy\byte-buddy\1.8.3\byte-buddy-1.8.3.jar;C:\Users\OSN20933\.m2\repository\org\apache\commons\commons-exec\1.3\commons-exec-1.3.jar;C:\Users\OSN20933\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\OSN20933\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\OSN20933\.m2\repository\org\apache\httpcomponents\httpcore\4.4.6\httpcore-4.4.6.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-support\3.12.0\selenium-support-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\seleniumhq\selenium\selenium-api\3.12.0\selenium-api-3.12.0.jar;C:\Users\OSN20933\.m2\repository\org\apache\httpcomponents\httpclient\4.5.5\httpclient-4.5.5.jar;C:\Users\OSN20933\.m2\repository\cglib\cglib\3.2.6\cglib-3.2.6.jar;C:\Users\OSN20933\.m2\repository\org\ow2\asm\asm\6.0\asm-6.0.jar;C:\Users\OSN20933\.m2\repository\org\apache\ant\ant\1.9.6\ant-1.9.6.jar;C:\Users\OSN20933\.m2\repository\org\apache\ant\ant-launcher\1.9.6\ant-launcher-1.9.6.jar;C:\Users\OSN20933\.m2\repository\commons-validator\commons-validator\1.6\commons-validator-1.6.jar;C:\Users\OSN20933\.m2\repository\commons-beanutils\commons-beanutils\1.9.2\commons-beanutils-1.9.2.jar;C:\Users\OSN20933\.m2\repository\commons-digester\commons-digester\1.8.1\commons-digester-1.8.1.jar;C:\Users\OSN20933\.m2\repository\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\OSN20933\.m2\repository\org\apache\commons\commons-lang3\3.7\commons-lang3-3.7.jar;C:\Users\OSN20933\.m2\repository\commons-io\commons-io\2.6\commons-io-2.6.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-context\5.0.5.RELEASE\spring-context-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-aop\5.0.5.RELEASE\spring-aop-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-beans\5.0.5.RELEASE\spring-beans-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-core\5.0.5.RELEASE\spring-core-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-jcl\5.0.5.RELEASE\spring-jcl-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\springframework\spring-expression\5.0.5.RELEASE\spring-expression-5.0.5.RELEASE.jar;C:\Users\OSN20933\.m2\repository\org\aspectj\aspectjweaver\1.9.1\aspectjweaver-1.9.1.jar;C:\Users\OSN20933\.m2\repository\org\openpnp\opencv\3.2.0-1\opencv-3.2.0-1.jar;C:\Users\OSN20933\.m2\repository\com\github\temyers\cucumber-jvm-parallel-plugin\4.2.0\cucumber-jvm-parallel-plugin-4.2.0.jar;C:\Users\OSN20933\.m2\repository\org\apache\velocity\velocity\1.7\velocity-1.7.jar;C:\Users\OSN20933\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar;C:\Users\OSN20933\.m2\repository\io\cucumber\gherkin\3.2.0\gherkin-3.2.0.jar;C:\Users\OSN20933\.m2\repository\io\cucumber\gherkin-jvm-deps\1.0.4\gherkin-jvm-deps-1.0.4.jar;C:\Users\OSN20933\.m2\repository\org\projectlombok\lombok\1.16.10\lombok-1.16.10.jar;C:\Users\OSN20933\.m2\repository\com\google\guava\guava\23.0\guava-23.0.jar;C:\Users\OSN20933\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;C:\Users\OSN20933\.m2\repository\com\google\errorprone\error_prone_annotations\2.0.18\error_prone_annotations-2.0.18.jar;C:\Users\OSN20933\.m2\repository\com\google\j2objc\j2objc-annotations\1.1\j2objc-annotations-1.1.jar;C:\Users\OSN20933\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.14\animal-sniffer-annotations-1.14.jar;C:\Users\OSN20933\.m2\repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar;C:\Users\OSN20933\.m2\repository\org\jdom\jdom2\2.0.6\jdom2-2.0.6.jar;C:\Users\OSN20933\.m2\repository\net\masterthought\cucumber-reporting\3.8.0\cucumber-reporting-3.8.0.jar;C:\Users\OSN20933\.m2\repository\org\apache\logging\log4j\log4j-api\2.6\log4j-api-2.6.jar;C:\Users\OSN20933\.m2\repository\org\apache\logging\log4j\log4j-core\2.6\log4j-core-2.6.jar;C:\Users\OSN20933\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.5\jackson-databind-2.8.5.jar;C:\Users\OSN20933\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;C:\Users\OSN20933\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.5\jackson-core-2.8.5.jar;C:\Users\OSN20933\.m2\repository\velocity-tools\velocity-tools\1.4\velocity-tools-1.4.jar;C:\Users\OSN20933\.m2\repository\joda-time\joda-time\2.9.6\joda-time-2.9.6.jar;C:\Users\OSN20933\.m2\repository\net\lingala\zip4j\zip4j\1.3.2\zip4j-1.3.2.jar;C:\Users\OSN20933\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.24\plexus-utils-3.0.24.jar;C:\Users\OSN20933\.m2\repository\org\jsoup\jsoup\1.10.1\jsoup-1.10.1.jar;C:\Users\OSN20933\.m2\repository\com\googlecode\owasp-java-html-sanitizer\owasp-java-html-sanitizer\20160924.1\owasp-java-html-sanitizer-20160924.1.jar;C:\Users\OSN20933\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\OSN20933\.m2\repository\com\aventstack\extentreports\3.1.2\extentreports-3.1.2.jar;C:\Users\OSN20933\.m2\repository\org\freemarker\freemarker\2.3.23\freemarker-2.3.23.jar;C:\Users\OSN20933\.m2\repository\org\mongodb\mongodb-driver\3.3.0\mongodb-driver-3.3.0.jar;C:\Users\OSN20933\.m2\repository\org\mongodb\bson\3.3.0\bson-3.3.0.jar;C:\Users\OSN20933\.m2\repository\org\mongodb\mongodb-driver-core\3.3.0\mongodb-driver-core-3.3.0.jar;C:\Users\OSN20933\.m2\repository\org\apache\httpcomponents\httpmime\4.5.2\httpmime-4.5.2.jar;C:\Users\OSN20933\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\OSN20933\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\OSN20933\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar;C:\Users\OSN20933\.m2\repository\org\testng\testng\6.11\testng-6.11.jar;C:\Users\OSN20933\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\OSN20933\.m2\repository\org\im4java\im4java\1.4.0\im4java-1.4.0.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-junit\1.2.4\cucumber-junit-1.2.4.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-core\1.2.4\cucumber-core-1.2.4.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-html\0.2.3\cucumber-html-0.2.3.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-jvm-deps\1.0.5\cucumber-jvm-deps-1.0.5.jar;C:\Users\OSN20933\.m2\repository\info\cukes\gherkin\2.12.2\gherkin-2.12.2.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-java\1.2.4\cucumber-java-1.2.4.jar;C:\Users\OSN20933\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\OSN20933\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\OSN20933\.m2\repository\info\cukes\cucumber-testng\1.2.4\cucumber-testng-1.2.4.jar;C:\Users\OSN20933\.m2\repository\com\madgag\animated-gif-lib\1.2\animated-gif-lib-1.2.jar;C:\Users\OSN20933\.m2\repository\com\github\lalyos\jfiglet\0.0.7\jfiglet-0.0.7.jar;C:\Users\OSN20933\.m2\repository\com\beust\jcommander\1.69\jcommander-1.69.jar;C:\Users\OSN20933\.m2\repository\com\github\SrinivasanTarget\DeviceManager\2fa96e0\DeviceManager-2fa96e0.jar;C:\Users\OSN20933\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\OSN20933\.m2\repository\com\github\yunusmete\stf\openstf-java-client\1.0\openstf-java-client-1.0.jar;C:\Users\OSN20933\.m2\repository\com\squareup\retrofit\retrofit\1.9.0\retrofit-1.9.0.jar;C:\Users\OSN20933\.m2\repository\com\squareup\okhttp3\okhttp\3.9.1\okhttp-3.9.1.jar;C:\Users\OSN20933\.m2\repository\com\squareup\okio\okio\1.13.0\okio-1.13.0.jar;C:\Users\OSN20933\.m2\repository\org\json\json\20171018\json-20171018.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.6\plugins\testng\lib\jcommander.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket58114 @w@C:\Users\OSN20933\AppData\Local\Temp\idea_working_dirs_testng.tmp -temp C:\Users\OSN20933\AppData\Local\Temp\idea_testng.tmp
java.lang.NullPointerException
	at com.appium.manager.LocalAppiumManager.getDevices(LocalAppiumManager.java:85)
	at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:133)
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:54)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.android.AndroidDeviceConfiguration.<init>(AndroidDeviceConfiguration.java:22)
	at com.video.recorder.Flick.<init>(Flick.java:24)
	at com.appium.manager.TestLogger.<init>(TestLogger.java:43)
	at com.appium.manager.ReportManager.<init>(ReportManager.java:32)
	at com.appium.manager.AppiumParallelTestListener.<init>(AppiumParallelTestListener.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:65)
	at org.testng.TestNG.addListeners(TestNG.java:1012)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:976)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
java.lang.NullPointerException
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:71)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.android.AndroidDeviceConfiguration.<init>(AndroidDeviceConfiguration.java:22)
	at com.video.recorder.Flick.<init>(Flick.java:24)
	at com.appium.manager.TestLogger.<init>(TestLogger.java:43)
	at com.appium.manager.ReportManager.<init>(ReportManager.java:32)
	at com.appium.manager.AppiumParallelTestListener.<init>(AppiumParallelTestListener.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:65)
	at org.testng.TestNG.addListeners(TestNG.java:1012)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:976)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
	at com.appium.manager.DeviceAllocationManager.isPlatformInEnv(DeviceAllocationManager.java:59)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:35)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.AppiumParallelTestListener.<init>(AppiumParallelTestListener.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:65)
	at org.testng.TestNG.addListeners(TestNG.java:1012)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:976)
	at org.testng.TestNG.run(TestNG.java:1102)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

Process finished with exit code -1
Empty test suite.

**Comment by saikrishna321** [comment]
You can't run testng.xml directly. 

This is the entry file https://github.com/saikrishna321/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/ParallelThread.java


Example: https://github.com/saikrishna321/PageObjectPatternAppium
