### ISSUE TITLE
Can not run test in real iOS device

### ISSUE THREAD

**Issue by ssrikantasahoo** [AppiumTestDistribution/AppiumTestDistribution#374]
version:ef39d1cdd0686bb6050bf9836264580fb0101640

Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
org.json.JSONException: JSONObject["deviceManufacturer"] not found.
	at org.json.JSONObject.get(JSONObject.java:520)
	at org.json.JSONObject.getString(JSONObject.java:806)
	at com.thoughtworks.device.Device.<init>(Device.java:65)
	at com.thoughtworks.iOS.IOSManager.lambda$getDevices$2(IOSManager.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.thoughtworks.iOS.IOSManager.getDevices(IOSManager.java:39)
	at com.appium.manager.LocalAppiumManager.getDevices(LocalAppiumManager.java:97)
	at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:133)
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:54)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
java.lang.NullPointerException
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:71)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.526 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 1.86 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.manager.ArtifactsUploader.initializeArtifacts(ArtifactsUploader.java:44)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:39)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:13)

Results :

Failed tests: 
  Runner.testRunner:13 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by saikrishna321** [comment]
@SrinivasanTarget ping

**Comment by ssrikantasahoo** [comment]
@saikrishna321 @SrinivasanTarget  any update

**Comment by ssrikantasahoo** [comment]
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
org.json.JSONException: JSONObject["deviceManufacturer"] not found.
	at org.json.JSONObject.get(JSONObject.java:520)
	at org.json.JSONObject.getString(JSONObject.java:806)
	at com.thoughtworks.device.Device.<init>(Device.java:65)
	at com.thoughtworks.iOS.IOSManager.lambda$getDevices$2(IOSManager.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.thoughtworks.iOS.IOSManager.getDevices(IOSManager.java:39)
	at com.appium.manager.LocalAppiumManager.getDevices(LocalAppiumManager.java:97)
	at com.appium.utils.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:133)
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:54)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
java.lang.NullPointerException
	at com.appium.utils.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:71)
	at com.appium.utils.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:38)
	at com.appium.utils.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:46)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:37)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.169 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 10.719 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at com.appium.manager.ArtifactsUploader.initializeArtifacts(ArtifactsUploader.java:44)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:39)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:52)
	at com.appium.manager.ParallelThread.<init>(ParallelThread.java:54)
	at com.appium.tests.Runner.testRunner(Runner.java:15)


Results :

Failed tests: 
  Runner.testRunner:15 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] --------------------------

**Comment by saikrishna321** [comment]
@ssrikantasahoo can u pls use the latest commit from master

**Comment by saikrishna321** [comment]
The framework will pick the UDID of the device automatically. Please update the version 9.1.0

**Comment by orvilia** [comment]
Thanks !! Version 9.1.0 of ATD ???

**Comment by saikrishna321** [comment]
yes ATD version

**Comment by orvilia** [comment]
I will just declare in POM right ??

**Comment by saikrishna321** [comment]
yup
