### ISSUE TITLE
Port Issue when running in distributed mode

### ISSUE THREAD

**Issue by narayan907** [AppiumTestDistribution/AppiumTestDistribution#442]
I am getting this issues when running in distributed mode, I think its not get free port to start appium session, please help to solve this issue.
org.openqa.selenium.WebDriverException: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:34361
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'qa-automation', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-42-generic', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /home/jenkins/workspace/utp..., appActivity: com.games24x7.android.games..., appPackage: com.games24x7.teenpatti.pla..., automationName: UIAutomator2, databaseEnabled: false, desired: {app: /home/jenkins/workspace/utp..., appActivity: com.games24x7.android.games..., appPackage: com.games24x7.teenpatti.pla..., automationName: UIAutomator2, deviceName: android, fullReset: false, newCommandTimeout: 100, noReset: true, noSign: true, platformName: android, platformVersion: 7.0, systemPort: 34361, udid: c9cdce08}, deviceApiLevel: 27, deviceManufacturer: vivo, deviceModel: vivo 1723, deviceName: c9cdce08, deviceScreenDensity: 480, deviceScreenSize: 1080x2280, deviceUDID: c9cdce08, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 100, noReset: true, noSign: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 8.1.0, statBarHeight: 96, systemPort: 34361, takesScreenshot: true, udid: c9cdce08, viewportRect: {height: 984, left: 0, top: 96, width: 2058}, warnings: {}, webStorageEnabled: false}
Session ID: 4ae8ca46-c42e-421f-a547-4504ffff3fd7
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)

**Comment by saikrishna321** [comment]
@narayan907 Pls post full logs

**Comment by narayan907** [comment]
2019-02-13 20:21:35
org.openqa.selenium.WebDriverException: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:34361
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'qa-automation', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-42-generic', java.version: '1.8.0_191'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /home/jenkins/workspace/utp..., appActivity: com.games24x7.android.games..., appPackage: com.games24x7.teenpatti.pla..., automationName: UIAutomator2, databaseEnabled: false, desired: {app: /home/jenkins/workspace/utp..., appActivity: com.games24x7.android.games..., appPackage: com.games24x7.teenpatti.pla..., automationName: UIAutomator2, deviceName: android, fullReset: false, newCommandTimeout: 100, noReset: true, noSign: true, platformName: android, platformVersion: 7.0, systemPort: 34361, udid: c9cdce08}, deviceApiLevel: 27, deviceManufacturer: vivo, deviceModel: vivo 1723, deviceName: c9cdce08, deviceScreenDensity: 480, deviceScreenSize: 1080x2280, deviceUDID: c9cdce08, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 100, noReset: true, noSign: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 8.1.0, statBarHeight: 96, systemPort: 34361, takesScreenshot: true, udid: c9cdce08, viewportRect: {height: 984, left: 0, top: 96, width: 2058}, warnings: {}, webStorageEnabled: false}
Session ID: 4ae8ca46-c42e-421f-a547-4504ffff3fd7
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:276)
at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)
at io.appium.java_client.MobileElement.execute(MobileElement.java:1)
at io.appium.java_client.android.AndroidElement.execute(AndroidElement.java:1)
at org.openqa.selenium.remote.RemoteWebElement.clear(RemoteWebElement.java:118)
at com.games24x7.core.utils.web_driver.WebDriverUtils.sendKeys(WebDriverUtils.java:587)
at com.games24x7.core.utils.web_driver.WebDriverUtils.sendCommand(WebDriverUtils.java:603)
at com.games24x7.core.utils.web_driver.WebDriverUtils.sendCommandAndGetOutput(WebDriverUtils.java:623)
at com.games24x7.core.model.page_objects.SignInPage.clickOnGuestandAllowPermissions(SignInPage.java:270)
at com.games24x7.core.model.page_objects.SignInPage.loginAsGuest(SignInPage.java:115)
at com.games24x7.utp.e2e.SignInTest.loginAsGuest(SignInTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748

**Comment by saikrishna321** [comment]
@narayan907 This is not full logs from ATD

**Comment by narayan907** [comment]
[consoleText.txt](https://github.com/AppiumTestDistribution/AppiumTestDistribution/files/2861242/consoleText.txt)
please look into test case "loginAsGuest"

**Comment by saikrishna321** [comment]
This is something to do with UIAutomator2 server stopped responding. Not related to ATD

**Comment by narayan907** [comment]
but from the error it looks like the port is not available.

**Comment by saikrishna321** [comment]
@narayan907 I'm sure it's not _port is not available_ issue. ATD gets free ports from the machine
