### ISSUE TITLE
Getting Null pointer when running against real ios device

### ISSUE THREAD

**Issue by sivaganesh1988** [AppiumTestDistribution/AppiumTestDistribution#443]
Getting below error when executing scripts. I am using version 10 of ATD

Java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at com.appium.executor.MyTestExecutor.writeTestNGFile(MyTestExecutor.java:289)
	at com.appium.executor.MyTestExecutor.constructXmlSuiteForDistributionMethods(MyTestExecutor.java:281)
	at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:80)
	at com.appium.manager.ATDRunner.parallelExecution(ATDRunner.java:124)
	at com.appium.manager.ATDRunner.triggerTest(ATDRunner.java:81)
	at com.appium.manager.ATDRunner.runner(ATDRunner.java:73)
	at com.appium.manager.ATDRunner.runner(ATDRunner.java:77)
	at com.mop.qa.testrunner.ATDTestRunner.testApp(ATDTestRunner.java:43)

**Comment by sivaganesh1988** [comment]
Closing the issue.  Issue was i didnt update the config.properties file.

**Comment by saikrishna321** [comment]
What was missing in the properties ? 

Will fix the error message

**Comment by sivaganesh1988** [comment]
RUNNER_LEVEL=methods
SUITE_NAME=testApp
CATEGORY=sanity

These were missing in the config file. Also I have few queries is there a tag I can use in stackoverflow for the questions ?

**Comment by spartanglady** [comment]
Hey Guys, I was trying to migrate from Extent Report to Report Portal. Now I'm pointing to the latest version of ATD and when I try to run the tests, I'm getting null pointer exception. Not sure if I have to add any new config parameters. I have added the reportportal.properties file.. 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.runners.Runner
Configuring TestNG with: TestNG652Configurator
ATD is Running on 127.0.0.1
OUTPUT DIRECTORY :/Users/(*&#(/WorkSpace/p2p-end-to-end-tests/target
     _  _       _          _  _             _         
  __| |(_) ___ | |_  _ __ (_)| |__   _   _ | |_   ___ 
 / _` || |/ __|| __|| '__|| || '_ \ | | | || __| / _ \
| (_| || |\__ \| |_ | |   | || |_) || |_| || |_ |  __/
 \__,_||_||___/ \__||_|   |_||_.__/  \__,_| \__| \___|
                                                      

***************************************************

Total Number of devices detected::1

***************************************************

Mar 23, 2019 2:22:00 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.105 sec <<< FAILURE! - in com.appium.tests.runners.Runner
testRunner(com.appium.tests.runners.Runner)  Time elapsed: 0.872 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at org.testng.xml.XmlSuite.toXml(XmlSuite.java:519)
        at com.appium.executor.MyTestExecutor.writeTestNGFile(MyTestExecutor.java:289)
        at com.appium.executor.MyTestExecutor.constructXmlSuiteForDistributionMethods(MyTestExecutor.java:281)
        at com.appium.executor.MyTestExecutor.runMethodParallelAppium(MyTestExecutor.java:80)
        at com.appium.manager.ATDRunner.parallelExecution(ATDRunner.java:124)
        at com.appium.manager.ATDRunner.triggerTest(ATDRunner.java:81)
        at com.appium.manager.ATDRunner.runner(ATDRunner.java:73)
        at com.appium.manager.ATDRunner.runner(ATDRunner.java:77)
        at com.appium.tests.runners.Runner.testRunner(Runner.java:17)


Results :

Failed tests: 
  Runner.testRunner:17 » NullPointer

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by saikrishna321** [comment]
config.properties should have SUITE_NAME=testApp and CATEGORY=sanity or can be set via Env

**Comment by spartanglady** [comment]
Works Now Thank you

**Comment by saikrishna321** [comment]
@sivaganesh1988 @spartanglady Fixed this in 10.0.1. Defaulting the values and also the RUNNE_LEVEL has been made optional
