### ISSUE TITLE
NullPointer Exception when using Before and After Annotation

### ISSUE THREAD

**Issue by MummanaSubramanya** [AppiumTestDistribution/AppiumTestDistribution#448]
I want to do some post steps after every test so I tried implementing Aftertest but I ended up in getting below exception.

 java.lang.NullPointerException
	at com.appium.utils.Helpers.isRetry(Helpers.java:77)
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:129)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)

**Comment by saikrishna321** [comment]
Can you post an example of your implementation?

**Comment by saikrishna321** [comment]
Closing as inactive.
