### ISSUE TITLE
SimulatorManager does not find any simulators

### ISSUE THREAD

**Issue by ValerioDR** [AppiumTestDistribution/AppiumTestDistribution#456]
Running my tests for iOS caused the exception **java.lang.RuntimeException: Device Not found with deviceName-iPhone X osVersion-12.2 osType-iOS**  which confused me because exactly this device was opened.

So i debugged the code and found the error, at least for my system.
Running the command **xcrun simctl list -j devices** gives me a response of the following kind:

```
"com.apple.CoreSimulator.SimRuntime.iOS-12-2" : [
      {
        "availability" : "(available)",
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        "udid" : "C7A3B837-0C84-4302-B327-DA12460BECF4",
        "availabilityError" : ""
      },....
```

Whats causing the error is the key **com.apple.CoreSimulator.SimRuntime.iOS-12-2** which is splitted by " ". So the follwoing code inside the Device constructor for Decoding  the JSON fails.

```
String[] osAndVersion = deviceType.split(" ");
if (osAndVersion.length == 2) {
      this.os = osAndVersion[0];
      this.osVersion = osAndVersion[1];
}
```

**Comment by VinayakaMayura** [comment]
Can you share your capabilites.json file?

**Comment by ValerioDR** [comment]
```
{
  "android": {
    "platformName": "android",
    "platformVersion": "9.0",
    "app": "./build/app-debug.apk",
    "automationName":"UIAutomator2",
    "appPackage": "de.xxx.appname",
    "appActivity": ".SplashActivity",
    "deviceName": "android",
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/Appname.app"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone X",
          "OS": "12.2"
        },
        {
          "deviceName": "iPhone XS",
          "OS": "12.2"
        }
      ]
    }
  ]
}
```

**Comment by VinayakaMayura** [comment]
Can you verify below two things
1. What is your Xcode version
2. Provide the appiumServerPath like below
```
"hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "appiumServerPath": "/usr/local/lib/node_modules/appium/build/lib/main.js",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "12.1"
        }
      ]
    }
```

**Comment by ValerioDR** [comment]
Still the same error.
XCode version is 10.2.1

**Comment by VinayakaMayura** [comment]
In Simulator the OS version should be changed to 10.2.1 then

**Comment by ValerioDR** [comment]
Mh, i dont think that makes any sense. The OS version of my simulator is iOS 12.2. 
The XCode version is not connected with my simulator version, which is proven by the command  **xcrun simctl list** which gives me the list of all availabel simulators on my system.

For example the iOS 12.2 simulators:
```
-- iOS 12.2 --
    iPhone 5s (C7A3B837-0C84-4302-B327-DA12460BECF4) (Shutdown) 
    iPhone 6 (B5CA6E87-B14D-4E52-8139-1E607E0F819D) (Shutdown) 
    iPhone 6 Plus (8B390502-80DA-460C-8F21-233E5AB63DCF) (Shutdown) 
    iPhone 6s (386F4099-A211-44D4-8513-97E5A3881B40) (Shutdown) 
    iPhone 6s Plus (2204E09B-5C7D-4C11-9147-8089776EEE0B) (Shutdown) 
    iPhone 7 (74D01C8B-D1EB-4D61-8772-084575C5A809) (Shutdown) 
    iPhone 7 Plus (0C89A504-D7D0-423E-9776-9C3607CD5EF7) (Shutdown) 
    iPhone 8 (9AA9F5A5-A099-4249-BD2F-AB6A55EF7FB0) (Shutdown) 
    iPhone 8 Plus (1601D86C-E90A-4EAB-A7B9-9D34197A29CF) (Shutdown) 
    iPhone SE (136B623B-28B5-450B-BA8E-9312A7B78FC3) (Shutdown) 
    iPhone X (5C77CB9A-1338-46B7-9AF0-F7E1935850AD) (Booted) 
    iPhone Xs (173AACDA-FD06-4515-8D63-7A02782C4926) (Shutdown) 
    iPhone Xs Max (50B2F683-0002-4EFD-A76A-5531A6B55F9A) (Shutdown) 
    iPhone Xʀ (E2D58096-317F-4CCD-80B0-C046A84D5C4A) (Booted) 
    iPad Air (3rd generation) (9A1BB46D-BC6B-4CB4-A5DA-B256668D68FD) (Shutdown) 
    iPad Air (B466BF49-51D8-4513-B071-EDCEB7FE8AD0) (Shutdown) 
    iPad Air 2 (3262A71E-AF8D-4917-BBE9-E6123D7EE3A0) (Shutdown) 
    iPad (5th generation) (1B1A733E-D936-44E9-93B5-BFBC11904FC7) (Shutdown) 
    iPad Pro (9.7-inch) (F53F3508-D0F7-446B-B56B-CFD360956CCE) (Shutdown) 
    iPad Pro (12.9-inch) (DBC6517A-8B1B-4366-B621-3D125B9A18FC) (Shutdown) 
    iPad Pro (12.9-inch) (2nd generation) (A1D89E71-DD99-4B3E-8CB0-049A4A095E95) (Shutdown) 
    iPad Pro (10.5-inch) (2F103BE1-C049-465F-8618-2FD8B0978E76) (Shutdown) 
    iPad (6th generation) (B196346E-815D-4520-A2D9-C58B7D670EDA) (Shutdown) 
    iPad Pro (11-inch) (2FF78873-4A95-4EA3-81FA-674CB7B2BDF1) (Shutdown) 
    iPad Pro (12.9-inch) (3rd generation) (AA7B0759-9F5B-4DEB-B7F0-3968E69413C1) (Shutdown) 
```

Nevertheless, i tried your advice, but unfortunately, it didn't work.

**Comment by VinayakaMayura** [comment]
Please let me know which version of ATD you are using.

Also i noticed, you have provided iPhoneX and iPhoneXS in capabilities but iPhoneXS is not booted



```
iPhone Xs (173AACDA-FD06-4515-8D63-7A02782C4926) (Shutdown)

**Comment by ValerioDR** [comment]
Also with removed iPhone XS capability i get the same Device not found error.
Im using ATD 10.0.1

**Comment by saikrishna321** [comment]
@ValerioDR Can you please post the complete exception?

**Comment by ValerioDR** [comment]
```
java.lang.RuntimeException: Device Not found with deviceName-iPhone X osVersion-12.2 osType-iOS
	at com.github.device.SimulatorManager.lambda$getDevice$2(SimulatorManager.java:45)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.device.SimulatorManager.getDevice(SimulatorManager.java:44)
	at com.appium.manager.LocalAppiumManager.getSimulator(LocalAppiumManager.java:111)
	at com.appium.device.HostMachineDeviceManager.getSimulatorsToBoot(HostMachineDeviceManager.java:199)
	at com.appium.device.HostMachineDeviceManager.getDevicesByIP(HostMachineDeviceManager.java:141)
	at com.appium.device.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:166)
	at com.appium.device.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:60)
	at com.appium.device.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:44)
	at com.appium.device.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:52)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:25)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:36)
	at com.appium.manager.ATDRunner.<init>(ATDRunner.java:45)
	at ios.tests.Runner.testRunner(Runner.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

I fixed it on my system by changing the device decoding to the following:

```
String[] splittedKey = deviceType.split("\\.");
if (splittedKey.length == 5) {
            String[] osAndVersion = splittedKey[splittedKey.length - 1].split("-");
            if (osAndVersion.length == 3) {
                this.os = osAndVersion[0];
                this.osVersion = osAndVersion[1] + "." + osAndVersion[2];
      }
}
```

Maybe the key format changed due to simctl updates. At least the above code is working for me when i start the tests from the IDE.

**Comment by saikrishna321** [comment]
@ValerioDR Thanks for the logs and your solution. Will be happy to accept a PR.

**Comment by saikrishna321** [comment]
@shridharkalagi @VinayakaMayura Do you wanna pick this and fix?

**Comment by saikrishna321** [comment]
Fix in master
