### ISSUE TITLE
Unable to launch already installed app on iOS

### ISSUE THREAD

**Issue by cesar-montoya** [AppiumTestDistribution/AppiumTestDistribution#459]
Logs:

Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
required key [app] not found
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.418 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.136 sec  <<< FAILURE!
org.everit.json.schema.ValidationException: #: Capability json provided is missing the above schema
        at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:37)
        at com.appium.manager.ATDRunner.<init>(ATDRunner.java:44)
        at com.appium.tests.Runner.testRunner(Runner.java:14)

Below are my capabilities.json for iOS
"iOS": {

    "platformName": "iOS",
    "bundleId": "com.*.*.*",
    "deviceName": "iphone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "locationServicesEnabled": true,
    "locationServicesAuthorized": true,
    "autoAcceptAlerts": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false
}

**Comment by saikrishna321** [comment]
Thanks for reporting. This is a bug and will fix it soon.

**Comment by saikrishna321** [comment]
@cesar-montoya As workaround can you please provide the _app_ capability and try with _bundleId_

**Comment by cesar-montoya** [comment]
@saikrishna321 
I tried this:
"app": "com.x.x.x",

but I got this error:
expected type: JSONObject, found: String

**Comment by saikrishna321** [comment]
@cesar-montoya Thanks for looking at this. Will get the fix by EOD. 
 
Question: So you have the app installed on the device and you don't have the IPA path in the caps?

**Comment by cesar-montoya** [comment]
@saikrishna321 yes, exactly.   I removed the IPA path from the caps as I want to run the installed version of the app. I have the IPA / APK files as a workaround.  
Thank you so much for fixing it, I really appreciate it.

**Comment by saikrishna321** [comment]
@cesar-montoya Can you try with this version 


```

   <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

       <dependency>
            <groupId>com.github.AppiumTestDistribution</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>fix-459-72d270067d-1</version>
        </dependency>

```

**Comment by cesar-montoya** [comment]
@saikrishna321  I have tried it with the below capabilities:
    "autoGrantPermissions": "true",
    "autoAcceptAlerts": "true",
    "platformName": "iOS",
    "bundleId": "com.*.*.was",
    "deviceName": "iphone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "locationServicesEnabled": true,
    "locationServicesAuthorized": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false,
    "updatedWDABundleId": "com.*.WebDriverAgentRunner",
    "xcodeOrgId": "*",
    "xcodeSigningId": "iPhone Developer"

**and got this error:**
Configuring TestNG with: TestNG652Configurator
org.json.JSONException: JSONObject["isCloud"] not found.

**Comment by saikrishna321** [comment]
@cesar-montoya Thanks for testing. Can you please try the below version? Please full exception logs
```
        <dependency>
            <groupId>com.github.AppiumTestDistribution</groupId>
            <artifactId>AppiumTestDistribution</artifactId>
            <version>97f11b580c</version>
        </dependency>
```

**Comment by cesar-montoya** [comment]
2019-05-29 15:39:47:845 [Appium] Welcome to Appium v1.13.0
2019-05-29 15:39:47:846 [Appium] Non-default server args:
2019-05-29 15:39:47:847 [Appium]   address: 127.0.0.1
2019-05-29 15:39:47:847 [Appium]   port: 32519
2019-05-29 15:39:47:847 [Appium]   logFile: /Users/cesarmontoya/Desktop/QA/Automationn/target/appiumlogs/appium_logs.txt
2019-05-29 15:39:47:847 [Appium]   relaxedSecurityEnabled: true
2019-05-29 15:39:47:889 [Appium] Appium REST http interface listener started on 127.0.0.1:32519
2019-05-29 15:39:48:088 [HTTP] --> GET /wd/hub/status
2019-05-29 15:39:48:088 [HTTP] {}
2019-05-29 15:39:48:090 [GENERIC] Calling AppiumDriver.getStatus() with args: []
2019-05-29 15:39:48:092 [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.13.0"}}
2019-05-29 15:39:48:096 [HTTP] <-- GET /wd/hub/status 200 6 ms - 68
2019-05-29 15:39:48:096 [HTTP] 
2019-05-29 15:39:48:169 [Appium] Received SIGTERM - shutting down
2019-05-29 15:39:48:174 uncaughtException: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)

**Comment by cesar-montoya** [comment]
May 29, 2019 11:39:48 AM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@22efb8b9 for Execution
org.json.JSONException: JSONObject["ios"] not found.
        at org.json.JSONObject.get(JSONObject.java:520)
        at org.json.JSONObject.getJSONObject(JSONObject.java:732)
        at com.appium.capabilities.DesiredCapabilityBuilder.desiredCapabilityForLocalAndRemoteATD(DesiredCapabilityBuilder.java:103)
        at com.appium.capabilities.DesiredCapabilityBuilder.buildDesiredCapability(DesiredCapabilityBuilder.java:54)
        at com.appium.manager.AppiumDriverManager.buildDesiredCapabilities(AppiumDriverManager.java:115)
        at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:92)
        at com.appium.manager.AppiumParallelTestListener.onTestStart(AppiumParallelTestListener.java:152)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1739)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:640)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:744)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
java.lang.NullPointerException
        at com.appium.utils.ScreenShotManager.captureScreenShot(ScreenShotManager.java:78)
        at com.appium.manager.TestLogger.handleTestFailure(TestLogger.java:156)
        at com.appium.manager.TestLogger.endLogging(TestLogger.java:81)
        at com.appium.manager.AppiumParallelTestListener.afterInvocation(AppiumParallelTestListener.java:81)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
        at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:713)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:744)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
        at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
May 29, 2019 11:39:48 AM com.appium.manager.DeviceAllocationManager freeDevice
INFO: DeAllocated Device 68783334ff0072cd178c08cb96ea55950d39d4c8 from execution list

**Comment by saikrishna321** [comment]
Please refer to the sample caps.json. You're missing the "iOS" object

https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/caps/capabilities.json#L11-L24

**Comment by cesar-montoya** [comment]
@saikrishna321 I am not :(
 "iOS": {
    "platformName": "iOS",
    "noReset": "true",
    "bundleId": "com.*.*.*",
    "autoGrantPermissions": "true",
    "autoAcceptAlerts": "true",
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": false,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "locationServicesEnabled": true,
    "locationServicesAuthorized": true,
    "maxTypingFrequency": 10,
    "isHeadless": false,
    "fullReset": false,
    "updatedWDABundleId": "com.yinzcam.WebDriverAgentRunner",
    "xcodeOrgId": "",
    "xcodeSigningId": "iPhone Developer"
  },

**Comment by saikrishna321** [comment]
Can you please post your execution command and full caps.json file

**Comment by saikrishna321** [comment]
@cesar-montoya Fix is in master. Can you please validate
