### ISSUE TITLE
Capability json provided is missing the above schema

### ISSUE THREAD

**Issue by zarashima** [AppiumTestDistribution/AppiumTestDistribution#506]
I seem to pass a correct desired capabilities in .json file to execute tests on iOS device, e.g:
```
{
  "iOS": {
    "app": "myPath",
    "platformName": "iOS",
    "automationName": "XCUITest",
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10,
    "xcodeOrgId": "myOrgId",
    "xcodeSigningId": "mySigningId"
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.4"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.4"
        }
      ]
    }
  ]
}
```

When I execute my tests, the following error is displayed:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.716 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.175 sec  <<< FAILURE!
org.everit.json.schema.ValidationException: #: Capability json provided is missing the above schema
        at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:37)
        at com.appium.manager.ATDRunner.<init>(ATDRunner.java:44)
        at com.appium.tests.Runner.testRunner(Runner.java:12)
```

Is there anything wrong here?

**Comment by saikrishna321** [comment]
Which version of ATD ?

**Comment by zarashima** [comment]
I'm using `10.0.1` version

**Comment by zarashima** [comment]
So is is an issue from ATD?

**Comment by saikrishna321** [comment]
Can you please post full logs

**Comment by zarashima** [comment]
More logs are shown below:

```
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
expected type: JSONObject, found: String
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.464 sec <<< FAILURE! - in com.appium.tests.Runner
testRunner(com.appium.tests.Runner)  Time elapsed: 0.191 sec  <<< FAILURE!
org.everit.json.schema.ValidationException: #: Capability json provided is missing the above schema
        at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:37)
        at com.appium.manager.ATDRunner.<init>(ATDRunner.java:44)
        at com.appium.tests.Runner.testRunner(Runner.java:12)


Results :

Failed tests: 
  Runner.testRunner:12 » Validation #: Capability json provided is missing the a...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.127 s
[INFO] Finished at: 2019-07-02T19:50:22+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/vinh.nguyen/Desktop/QA/SVN/testautomation/FunctionalTests/Appium/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project PagePatternAppium: There are test failures.

Please refer to /Users/xxx/target/surefire-reports for the individual test results.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /Users/xxxx/target/surefire-reports for the individual test results.
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:82)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:254)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:854)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:722)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by saikrishna321** [comment]
This is my capabilities.json
```
{
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "./build/WordPress.zip"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "usePrebuiltWDA": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 7",
          "OS": "11.4"
        }
      ]
    }
  ]
}
```

Can you try with below 

```

{
  "iOS": {
    "app": {
      "device": ".pathtofile.ipa"
    },
    "platformName": "iOS",
    "automationName": "XCUITest",
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10,
    "xcodeOrgId": "myOrgId",
    "xcodeSigningId": "mySigningId"
  },
  "hostMachines": [
    {
      "machineIP": "127.0.0.1",
      "simulators": [
        {
          "deviceName": "iPhone 6",
          "OS": "11.4"
        },
        {
          "deviceName": "iPhone 7",
          "OS": "11.4"
        }
      ]
    }
  ]
}

```

**Comment by zarashima** [comment]
Hi,

It works now. I miss "device" node in "app" node, so that's why. Thanks for your help.

Regards
