### ISSUE TITLE
failed to execute goal due to com.pagepattern.appium:PagePatternAppium:jar:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by siva90144** [AppiumTestDistribution/AppiumTestDistribution#543]
Just cloned this project: https://github.com/AppiumTestDistribution/PageObjectPatternAppium 

and executed below goal.
mvn goal: clean test -Dtest=RunnerCukes test -DPlatform=android

The POM for com.github.AppiumTestDistribution:DeviceManager:jar:17b2681e6a is missing, no dependency information available
[WARNING] The POM for com.github.everit-org.json-schema:org.everit.json.schema:jar:1.11.1 is missing, no dependency information available

Failed to execute goal on project PagePatternAppium: Could not resolve dependencies for project com.pagepattern.appium:PagePatternAppium:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.github.AppiumTestDistribution:DeviceManager:jar:17b2681e6a, com.github.everit-org.json-schema:org.everit.json.schema:jar:1.11.1: Failure to find com.github.AppiumTestDistribution:DeviceManager:jar:17b2681e6a in http://artifactory.prod.asurion.net:8081/artifactory/mvn-deps-release was cached in the local repository, resolution will not be reattempted until the update interval of libs-release has elapsed or updates are forced -> [Help 1]

**Comment by saikrishna321** [comment]
Looks like you have issues downloading dependency

**Comment by siva90144** [comment]
I tried on different machines .... but getting the same error.

**Comment by vannt1991** [comment]
> Now I reimported (Ecplise)the project and getting below error.
> I passed the maven goal as below for cucumber test
> 
> Goal:
> ![goal](https://user-images.githubusercontent.com/19613704/64084220-0be42400-ccf7-11e9-83bc-e4b366253093.PNG)
> -DPlatform=android clean -Dtest=Runner test
> 
> Running com.appium.tests.Runner
> Configuring TestNG with: TestNG652Configurator
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.862 sec <<< FAILURE! - in com.appium.tests.Runner
> testRunner(com.appium.tests.Runner) Time elapsed: 0.124 sec <<< FAILURE!
> java.lang.IllegalArgumentException: Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
> at com.appium.schema.CapabilitySchemaValidator.isPlatformInEnv(CapabilitySchemaValidator.java:68)
> at com.appium.schema.CapabilitySchemaValidator.validateCapabilitySchema(CapabilitySchemaValidator.java:26)
> at com.appium.manager.ATDRunner.(ATDRunner.java:46)
> at com.appium.tests.Runner.testRunner(Runner.java:13)

i have the same issue when run sample **PagePatternAppium** project in Windown 10, any one have solution to work through with this issue? please help us. Thanks!

**Comment by saikrishna321** [comment]
Platform=android  should be set as env

**Comment by vannt1991** [comment]
> > > Please execute with Platform environment:: Platform=android/ios/both mvn clean -Dtest=Runner test
> 
> `Platform=android` should be set as env

Thanks for reply, after research i just fixed issue, but now i have another problem when i tries to run PagePatternAppium project in Windown 10 with Appium v1.15.1, here is error log afer run comman in terminal in Intelliji. You can see full logs [**here**](https://notepad.vn/dpvybuo86)

`java.lang.NullPointerException
        at com.appium.manager.TestLogger.isNativeAndroid(TestLogger.java:160)
        at com.appium.manager.TestLogger.endLogging(TestLogger.java:97)
        at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:129)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
        at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:713)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.lang.IllegalArgumentException: ItemID should not be null
        at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
        at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
        at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1731)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1250)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Oct 24, 2019 11:25:17 PM com.context.SessionContext addContext
INFO: Adding context for thread - 27
Oct 24, 2019 11:25:17 PM com.context.TestExecutionContext <init>
INFO: setUp - TestExecution context created
java.lang.NullPointerException
        at com.appium.manager.TestLogger.isNativeAndroid(TestLogger.java:160)
        at com.appium.manager.TestLogger.endLogging(TestLogger.java:97)
        at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:129)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:100)
        at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
        at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:545)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
In Skipped...
java.lang.IllegalArgumentException: ItemID should not be null
        at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
        at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
        at com.epam.reportportal.testng.BaseTestNGListener.onTestSkipped(BaseTestNGListener.java:103)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1723)
        at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
        at org.testng.internal.Invoker.registerSkippedTestResult(Invoker.java:1272)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:605)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Oct 24, 2019 11:25:17 PM com.context.SessionContext addContext
INFO: Adding context for thread - 27`

Could you give me a suggestion? Thanks!

**Comment by vannt1991** [comment]
@saikrishna321 here is my sample project, i'm working on Windown 10 with Appium v1.15.1, please help me review and give me a advice, thanks so much for your effort.
