### ISSUE TITLE
Not able to execute Tests on saucelabs cloud devices 

### ISSUE THREAD

**Issue by vigneshfreshworks** [AppiumTestDistribution/AppiumTestDistribution#568]
I have tried the exact capabilities mentioned here :

https://github.com/AppiumTestDistribution/AppiumTestDistribution/wiki/Configure-test-for-Cloud-Sauce

Note : I managed to run tests on saucelabs without ATD, capabilities i used , 

caps.setCapability("appiumVersion", "1.15.0");
		caps.setCapability("testobject_api_key","XXX");
		caps.setCapability("platformVersion","8");
		caps.setCapability("browserName", "");
		 caps.setCapability("test_object_app_id", "1");
		caps.setCapability("platformName","Android");
		caps.setCapability("testobject_suite_name", "Default Appium Suite");
		caps.setCapability("testobject_test_name", "Default Appium Test");
		driver = new IOSDriver<MobileElement>(new URL("https://us1- 
                manual.app.testobject.com/wd/hub"), caps);

I'm getting the below attached error when trying to execute using ATD : 

![image](https://user-images.githubusercontent.com/47552993/68021513-9b8e5a80-fcc7-11e9-84ca-c0a52dd76341.png)

**Comment by saikrishna321** [comment]
@vigneshfreshworks Can you pls post the entire log as gist

**Comment by vigneshfreshworks** [comment]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.appium.tests.Runner
Configuring TestNG with: TestNG652Configurator
Nov 01, 2019 4:27:30 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on ondemand.eu-central-1.saucelabs.com
      _   _         _            _   _               _          
   __| | (_)  ___  | |_   _ __  (_) | |__    _   _  | |_    ___ 
  / _` | | | / __| | __| | '__| | | | '_ \  | | | | | __|  / _ \
 | (_| | | | \__ \ | |_  | |    | | | |_) | | |_| | | |_  |  __/
  \__,_| |_| |___/  \__| |_|    |_| |_.__/   \__,_|  \__|  \___|
                                                                

Nov 01, 2019 4:27:30 PM com.appium.manager.ATDRunner parallelExecution
INFO: com.appium.manager.ATDRunnerTotal Number of devices detected::1

Nov 01, 2019 4:27:30 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
...
... TestNG 6.11 by Cédric Beust (cedric@beust.com)
...

log4j:WARN No appenders could be found for logger (rp.org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Nov 01, 2019 4:27:31 PM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@112b7716 for Execution
Nov 01, 2019 4:27:31 PM com.appium.manager.AppiumDriverManager getChromeVersionsFor
INFO: Chrome not found on device - 'null'
Nov 01, 2019 4:27:31 PM com.appium.manager.AppiumDriverManager initialiseDriver
INFO: Capabilities: Capabilities {app: /Users/vigneshgu/Documents/..., appActivity: com.freshservice.helpdesk.u..., appPackage: com.freshservice.helpdesk, automationName: UIAutomator2, browserName: , device: Motorola_Moto_G6_free, deviceName: Motorola_Moto_G6_free, noReset: true, noSign: true, platformName: android, platformVersion: 8.0.0, version: 8.0.0}
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Unable to parse remote response: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.17.1</center>
</body>
</html>

Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Vignesh-Guru.local', ip: 'fe80:0:0:0:1c89:a03d:1141:d638%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15', java.version: '1.8.0_202'
Driver info: driver.version: AppiumDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:77)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:146)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:156)
	at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:111)
	at com.appium.manager.AppiumParallelMethodTestListener.onTestStart(AppiumParallelMethodTestListener.java:72)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1739)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:640)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 26 more
Caused by: org.openqa.selenium.WebDriverException: Unable to parse remote response: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.17.1</center>
</body>
</html>

	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
	... 31 more
Caused by: org.openqa.selenium.json.JsonException: Unable to determine type from: <. Last 1 characters read: <
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Vignesh-Guru.local', ip: 'fe80:0:0:0:1c89:a03d:1141:d638%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15', java.version: '1.8.0_202'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.json.JsonInput.peek(JsonInput.java:122)
	at org.openqa.selenium.json.JsonTypeCoercer.lambda$null$6(JsonTypeCoercer.java:140)
	at org.openqa.selenium.json.JsonTypeCoercer.coerce(JsonTypeCoercer.java:126)
	at org.openqa.selenium.json.Json.toType(Json.java:69)
	at org.openqa.selenium.json.Json.toType(Json.java:55)
	at org.openqa.selenium.json.Json.toType(Json.java:50)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:112)
	... 31 more
Nov 01, 2019 4:27:33 PM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Nov 01, 2019 4:27:33 PM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Nov 01, 2019 4:27:33 PM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - /Users/vigneshgu/Documents/Appium/FreshService/src/test/resources/reportportal.properties
Nov 01, 2019 4:27:33 PM com.context.SessionContext <clinit>
INFO: Initialized SessionContext
Nov 01, 2019 4:27:33 PM com.context.SessionContext addContext
INFO: Adding context for thread - 18
Nov 01, 2019 4:27:33 PM com.context.TestExecutionContext <init>
INFO: TC_1209_VerifyTheFunctionalityOfTheDefaultTicketViews - TestExecution context created
java.lang.IllegalArgumentException: ItemID should not be null
	at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
	at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1731)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1250)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vigneshfreshworks** [comment]
https://gist.github.com/vigneshfreshworks/74caf9106efaa91aa8a6b3c537c271e3 

@saikrishna321  please find the logs

**Comment by saikrishna321** [comment]
@vigneshfreshworks Looks like ur keys are not authorized to cloud

```
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.17.1</center>
</body>
</html>

```

**Comment by vigneshfreshworks** [comment]
Hi @saikrishna321  I have added the API keys using capability "test_object_api_key", still getting the same error. 

do u have different solution for this   ?

**Comment by saikrishna321** [comment]
let me try creating a free account and give it a try. Will keep you posted

@WasiqB
