### ISSUE TITLE
demo's errored is 'no device connected'

### ISSUE THREAD

**Issue by hongbiangoal** [AppiumTestDistribution/AppiumTestDistribution#575]
Mac 10.14.6， atd11.0.1，
when set Platform = android,  error occur 
when set Platform = both,  nullpointexception

**Comment by saikrishna321** [comment]
Please provide more info with logs.

**Comment by hongbiangoal** [comment]
Platform = both:
LocalAppiumManagerAppium Server Started at......http://127.0.0.1:44167/wd/hub
java.lang.IllegalArgumentException: ItemID should not be null
	at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
	at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestSkipped(BaseTestNGListener.java:103)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1723)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.registerSkippedTestResult(Invoker.java:1272)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:605)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelMethodTestListener.isCloudExecution(AppiumParallelMethodTestListener.java:76)
	at com.appium.manager.AppiumParallelMethodTestListener.onTestSkipped(AppiumParallelMethodTestListener.java:194)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1723)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.registerSkippedTestResult(Invoker.java:1272)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:605)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: ItemID should not be null
	at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:247)
	at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:157)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestSkipped(BaseTestNGListener.java:103)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1723)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.registerSkippedTestResult(Invoker.java:1272)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:605)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelMethodTestListener.isCloudExecution(AppiumParallelMethodTestListener.java:76)
	at com.appium.manager.AppiumParallelMethodTestListener.onTestSkipped(AppiumParallelMethodTestListener.java:194)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1723)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1714)
	at org.testng.internal.Invoker.registerSkippedTestResult(Invoker.java:1272)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:605)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
FAILED CONFIGURATION: @BeforeMethod setUp
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelMethodTestListener.isCloudExecution(AppiumParallelMethodTestListener.java:76)
	at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:89)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:502)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hongbiangoal** [comment]
Platform = android:
ATD is Running on 127.0.0.1
      _   _         _            _   _               _          
   __| | (_)  ___  | |_   _ __  (_) | |__    _   _  | |_    ___ 
  / _` | | | / __| | __| | '__| | | | '_ \  | | | | | __|  / _ \
 | (_| | | | \__ \ | |_  | |    | | | |_) | | |_| | | |_  |  __/
  \__,_| |_| |___/  \__| |_|    |_| |_.__/   \__,_|  \__|  \___|
                                                                

  _   _             ____                   _                          ____                                         _                _ 
 | \ | |   ___     |  _ \    ___  __   __ (_)   ___    ___   ___     / ___|   ___    _ __    _ __     ___    ___  | |_    ___    __| |
 |  \| |  / _ \    | | | |  / _ \ \ \ / / | |  / __|  / _ \ / __|   | |      / _ \  | '_ \  | '_ \   / _ \  / __| | __|  / _ \  / _` |
 | |\  | | (_) |   | |_| | |  __/  \ V /  | | | (__  |  __/ \__ \   | |___  | (_) | | | | | | | | | |  __/ | (__  | |_  |  __/ | (_| |
 |_| \_|  \___/    |____/   \___|   \_/   |_|  \___|  \___| |___/    \____|  \___/  |_| |_| |_| |_|  \___|  \___|  \__|  \___|  \__,_|

**Comment by saikrishna321** [comment]
@hongbiangoal Are you using `@BeforeMethod` in your tests?

**Comment by hongbiangoal** [comment]
it seems appium not right
