### ISSUE TITLE
AppiumTestDistribution version bef9b5ac70 failed to run on any device

### ISSUE THREAD

**Issue by chuklov** [AppiumTestDistribution/AppiumTestDistribution#722]
I am having an issue running tests, any test after moving to a new version. New version needed to run test on iOS 13.X and on a new devices. 
Here is the failure:
`
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.17.1"}}
[HTTP] <-- GET /wd/hub/status 200 7 ms - 68
[HTTP] 
Aug 04, 2020 10:07:34 AM com.appium.manager.LocalAppiumManager startAppiumServer
INFO: LocalAppiumManagerAppium Server Started at......http://127.0.0.1:4473/wd/hub
Aug 04, 2020 10:07:34 AM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@256caa11 for Execution
Aug 04, 2020 10:07:34 AM com.appium.manager.AppiumDriverManager initialiseDriver
INFO: Capabilities: Capabilities {agentPath: /usr/local/lib/node_modules..., appiumVersion: 1.17.1, automationName: XCUITest, bootstrapPath: /usr/local/lib/node_modules..., bundleId: com.apple.mobilesafari, clearSystemFiles: true, deviceName: iPhone, newCommandTimeout: 600, noReset: true, platformName: ios, platformVersion: 13.4, preventWDAAttachments: true, udid: bd3ccfde1c14ef869656292b046..., useNewWDA: false, usePrebuiltWDA: true, wdaLocalPort: 53233, webkitDebugProxyPort: 53249, xcodeOrgId: 2ES97B4EP7, xcodeSigningId: iPhone Developer}
java.lang.NullPointerException
	at com.appium.manager.ScreenShotManager.captureScreenShot(ScreenShotManager.java:80)
	at com.appium.manager.TestLogger.handleTestFailure(TestLogger.java:193)
	at com.appium.manager.TestLogger.endLogging(TestLogger.java:111)
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:139)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:110)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:61)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:618)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
FAILED: testBadCode
**java.lang.NullPointerException
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:154)**
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:110)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:61)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:618)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

===============================================
    ATDTest
    Tests run: 1, Failures: 1, Skips: 0
===============================================

Aug 04, 2020 10:07:34 AM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Aug 04, 2020 10:07:34 AM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Aug 04, 2020 10:07:34 AM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - /Users/chuklova/IdeaProjects/autotest_mobile/src/test/resources/reportportal.properties
Aug 04, 2020 10:07:34 AM com.context.SessionContext <clinit>
INFO: Initialized SessionContext

===============================================
ATDSuiteName
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================
`

Execution is not going to my code at all, it fails before my code and right after this line 
`runner = parallelThread.runner("com.appium.tests", tests); `

Any ideas? 
Thanks

**Comment by saikrishna321** [comment]
Can you please try with 
```
<!-- https://mvnrepository.com/artifact/com.github.saikrishna321/AppiumTestDistribution -->
<dependency>
    <groupId>com.github.saikrishna321</groupId>
    <artifactId>AppiumTestDistribution</artifactId>
    <version>11.0.2</version>
</dependency>
```

**Comment by chuklov** [comment]
Hi Sai, 

Just tried and I have the following crash after parallelThread.runner


`[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.17.1"}}
[HTTP] <-- GET /wd/hub/status 200 5 ms - 68
[HTTP] 
Aug 11, 2020 1:33:40 PM com.appium.manager.LocalAppiumManager startAppiumServer
INFO: LocalAppiumManagerAppium Server Started at......http://127.0.0.1:5418/wd/hub
Aug 11, 2020 1:33:40 PM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@67b268eb for Execution
Aug 11, 2020 1:33:40 PM com.appium.manager.AppiumDriverManager initialiseDriver
INFO: Capabilities: Capabilities {agentPath: /usr/local/lib/node_modules..., appiumVersion: 1.17.1, automationName: XCUITest, bootstrapPath: /usr/local/lib/node_modules..., bundleId: com.apple.mobilesafari, clearSystemFiles: true, deviceName: iPhone, newCommandTimeout: 600, noReset: true, platformName: ios, platformVersion: 13.4, preventWDAAttachments: true, udid: bd3ccfde1c14ef869656292b046..., useNewWDA: false, usePrebuiltWDA: true, wdaLocalPort: 49668, webkitDebugProxyPort: 49686, xcodeOrgId: 2ES97B4EP7, xcodeSigningId: iPhone Developer}
java.lang.NullPointerException
	at com.appium.manager.ScreenShotManager.captureScreenShot(ScreenShotManager.java:80)
	at com.appium.manager.TestLogger.handleTestFailure(TestLogger.java:193)
	at com.appium.manager.TestLogger.endLogging(TestLogger.java:111)
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:139)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:110)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:61)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:618)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
FAILED: testBadCode
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:154)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeAfterInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:110)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:61)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:618)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


===============================================
    ATDTest
    Tests run: 1, Failures: 1, Skips: 0
===============================================

Aug 11, 2020 1:33:40 PM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Aug 11, 2020 1:33:40 PM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Aug 11, 2020 1:33:40 PM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - /Users/chuklova/IdeaProjects/autotest_mobile/src/test/resources/reportportal.properties
Aug 11, 2020 1:33:40 PM com.context.SessionContext <clinit>
INFO: Initialized SessionContext
[Appium] Received SIGTERM - shutting down
[debug] [Appium] There are no active sessions for cleanup

===============================================
ATDSuiteName
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================`

**Comment by saikrishna321** [comment]
@chuklov For some reason the driver creation is failing [here](https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/src/main/java/com/appium/manager/AppiumDriverManager.java#L60-L84) Can you keep breakpoints and check what is failing.

Have to pair on fixing this. Please send me zoom details to saikrishna321@yahoo.com

**Comment by chuklov** [comment]
@saikrishna321 
Version 11.0.2 also has an issue with starting Android tests. It is not failing but it stuck after the Appium Driver Manager and not going anywhere for hours.

**Comment by chuklov** [comment]
Here is an iOS failure: 
![Screen Shot 2020-08-12 at 9 27 00](https://user-images.githubusercontent.com/10007866/89982337-3451fd80-dc7e-11ea-94af-10368c8dbd2c.png)

**Comment by saikrishna321** [comment]
@chuklov I'm unable to reproduce this problem. Can you please try to replicate with the sample project - https://github.com/AppiumTestDistribution/PageObjectPatternAppium

**Comment by chuklov** [comment]
With simple project issue is not replicated. Only with ATD

**Comment by chuklov** [comment]
Did you open the project I have sent to you as I could replicate it on my
machine after I copy it from the google drive?

**Comment by saikrishna321** [comment]
@chuklov Yes I did and I was able to reproduce the issue. I see there is a dependency conflict due to which WebDriverManager creation fails quietly and hits the afterInvocation and as the session is not created it fails with NullPointer. 

From our side we will improve better Logging and Exception Handling. You need to find out which version of the dependency is conflicting in your project.

**Comment by chuklov** [comment]
@saikrishna321  This issue can be closed.
