### ISSUE TITLE
Failed to create session with iOS 12.2 after update to Appium 18.3 

### ISSUE THREAD

**Issue by chuklov** [AppiumTestDistribution/AppiumTestDistribution#757]
I have an issue with running tests on iOS 12.2 after I have updated to Appium server 18.3 and Appium Desktop 18.2 
Appium Desktop works fine and can connect. 
New project for Appium also works fine. 
Connection to iOS 13.6 and 14 also works fine. 
Xcode installation of WebDriver works fine. 

Issue only on my old project. Here is the error output: 

`
[DevCon Factory] Releasing connections for bd3ccfde1c14ef869656292b0460da522728aedc device on any port number
[DevCon Factory] Found cached connections to release: ["bd3ccfde1c14ef869656292b0460da522728aedc:59421"]
[DevCon Factory] Releasing the listener for 'bd3ccfde1c14ef869656292b0460da522728aedc:59421'
[debug] [iProxy@bd3ccfde:59421] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[iProxy@bd3ccfde:59421] The connection has been closed
[debug] [XCUITest] Did not find the temporary XCTest logs root at '/var/folders/4_/y_kblsms2q7_z01z3p84gn_cjbs_9f/T/com.apple.dt.XCTest*/'
[XCUITest] Cleaning test logs in '/Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs' folder
[debug] [iOS] Clearing log files
[debug] [iOS] Deleting '/Users/chuklova/Library/Developer/Xcode/DerivedData/WebDriverAgent-ciegwgvxzxdrqthilmrmczmqvrgu/Logs'. Freeing 132K.
[debug] [iOS] Finished clearing log files
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1602414824925 (14:13:44 GMT+0300 (Israel Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [W3C] xcodebuild error message:
[debug] [W3C] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [W3C]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:532:15)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:562:11
[debug] [W3C]     at wrapped (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[debug] [W3C]     at retry (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[debug] [W3C]     at retryInterval (/usr/local/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[debug] [W3C]     at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:542:7
[debug] [W3C] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 15749 ms - 1213
[HTTP] 
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:1869:6254:a0fd:4b7f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_241'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:1869:6254:a0fd:4b7f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_241'
Driver info: driver.version: IOSDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:336)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:88)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:98)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:90)
	at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:63)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:144)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:154)
	at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:120)
	at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:93)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:56)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:574)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 30 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Mac-mini-2.lan', ip: 'fe80:0:0:0:1869:6254:a0fd:4b7f%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.6', java.version: '1.8.0_241'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:381:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	... 35 more
Oct 11, 2020 2:13:45 PM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Oct 11, 2020 2:13:45 PM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Oct 11, 2020 2:13:45 PM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - /Users/chuklova/IdeaProjects/autotest_mobile/src/test/resources/reportportal.properties
Oct 11, 2020 2:13:45 PM com.context.SessionContext <clinit>
INFO: Initialized SessionContext
Oct 11, 2020 2:13:45 PM com.context.SessionContext addContext
INFO: Adding context for thread - 19
Oct 11, 2020 2:13:45 PM com.context.TestExecutionContext <init>
INFO: testPortScanning - TestExecution context created
Disconnected from the target VM, address: '127.0.0.1:59413', transport: 'socket'

`

**Comment by saikrishna321** [comment]
>> Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

Not ATD Issue. Please make sure WDA can build successfully

**Comment by chuklov** [comment]
Hi Sai, as I said, everything works fine, build in Xcode, build and run tests on a separate project, only on ATD project this phone getting this error.

**Comment by saikrishna321** [comment]
@chuklov But the error is not related to ATD. It's throwing from appium server. You need to check what different you are doing in ATD project and other one.
