### ISSUE TITLE
In windows, not able to run test (testNG runner) . error: [java.io.IOException: Cannot run program "/bin/sh": CreateProcess error=2,],error 2:[java.lang.NullPointerException 	at com.appium.manager.TestLogger.isNativeAndroid(],[Exception in thread "Thread_0" java.lang.IllegalArgumentException: ItemID should not be null]

### ISSUE THREAD

**Issue by nwintop** [AppiumTestDistribution/AppiumTestDistribution#782]
Nov 17, 2020 12:12:01 PM com.appium.utils.ConfigFileManager <clinit>
INFO: Using config file from [./configs/config.properties]
Nov 17, 2020 12:12:02 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on 127.0.0.1
      _   _         _            _   _               _          
   __| | (_)  ___  | |_   _ __  (_) | |__    _   _  | |_    ___ 
  / _` | | | / __| | __| | '__| | | | '_ \  | | | | | __|  / _ \
 | (_| | | | \__ \ | |_  | |    | | | |_) | | |_| | | |_  |  __/
  \__,_| |_| |___/  \__| |_|    |_| |_.__/   \__,_|  \__|  \___|
                                                                

Nov 17, 2020 12:12:04 PM com.appium.manager.ATDRunner parallelExecution
INFO: com.appium.manager.ATDRunnerTotal Number of devices detected::1

Nov 17, 2020 12:12:04 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
Nov 17, 2020 12:12:05 PM com.appium.utils.Helpers getStream
INFO: Custom Listener not found!!
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
...
... TestNG 7.0.1 by CÃ©dric Beust (cedric@beust.com)
...

Nov 17, 2020 12:12:06 PM com.appium.manager.LocalAppiumManager startAppiumServer
Picking UserSpecified Path for AppiumServiceBuilder
INFO: LocalAppiumManagerStarting Appium Server on Localhost
log4j:WARN No appenders could be found for logger (rp.org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[Appium] Welcome to Appium v1.18.3
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium]   port: 32655
[Appium]   logFile: C:\updatedRepo\2210\ResponsiveSeasonsTests\target\appiumlogs\appium_logs.txt
[Appium]   relaxedSecurityEnabled: true
[Appium] Appium REST http interface listener started on 127.0.0.1:32655
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.18.3"}}
[HTTP] <-- GET /wd/hub/status 200 7 ms - 68
[HTTP] 
Nov 17, 2020 12:12:09 PM com.appium.manager.LocalAppiumManager startAppiumServer
INFO: LocalAppiumManagerAppium Server Started at......http://127.0.0.1:32655/wd/hub
Nov 17, 2020 12:12:10 PM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@34c44c5e for Execution
java.io.IOException: Cannot run program "/bin/sh": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.appium.utils.CommandPrompt.getBufferedReader(CommandPrompt.java:45)
	at com.appium.utils.CommandPrompt.runCommandThruProcess(CommandPrompt.java:53)
	at com.appium.manager.AppiumDriverManager.getChromeVersionsFor(AppiumDriverManager.java:117)
	at com.appium.manager.AppiumDriverManager.getPathForChromeDriver(AppiumDriverManager.java:102)
	at com.appium.manager.AppiumDriverManager.addChromeDriverPathIfChromeOnDevice(AppiumDriverManager.java:92)
	at com.appium.manager.AppiumDriverManager.initialiseDriver(AppiumDriverManager.java:55)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:144)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:154)
	at com.appium.manager.AppiumParallelMethodTestListener.allocateDeviceAndStartDriver(AppiumParallelMethodTestListener.java:120)
	at com.appium.manager.AppiumParallelMethodTestListener.beforeInvocation(AppiumParallelMethodTestListener.java:93)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:56)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:574)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
	at java.lang.ProcessImpl.start(ProcessImpl.java:140)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more
Nov 17, 2020 12:12:10 PM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Nov 17, 2020 12:12:10 PM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Nov 17, 2020 12:12:10 PM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - C:\updatedRepo\2210\ResponsiveSeasonsTests\src\test\resources\reportportal.properties
Nov 17, 2020 12:12:10 PM com.context.SessionContext <clinit>
INFO: Initialized SessionContext
Nov 17, 2020 12:12:10 PM com.context.SessionContext addContext
INFO: Adding context for thread - 26
Nov 17, 2020 12:12:10 PM com.context.TestExecutionContext <init>
INFO: VerifyPreselectionOfTicketTypes - TestExecution context created
https://www.####.com
java.lang.NullPointerException
	at com.appium.manager.TestLogger.isNativeAndroid(TestLogger.java:160)
	at com.appium.manager.TestLogger.endLogging(TestLogger.java:97)
	at com.appium.manager.AppiumParallelMethodTestListener.afterInvocation(AppiumParallelMethodTestListener.java:139)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:60)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:631)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread_0" java.lang.IllegalArgumentException: ItemID should not be null
	at rp.com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.epam.reportportal.service.LaunchImpl.finishTestItem(LaunchImpl.java:252)
	at com.epam.reportportal.testng.TestNGService.finishTestMethod(TestNGService.java:152)
	at com.epam.reportportal.testng.BaseTestNGListener.onTestFailure(BaseTestNGListener.java:98)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:826)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code -1

**Comment by nwintop** [comment]
this was the code issue now it handled for both mac and windows. fixed now.
