### ISSUE TITLE
Not able to run tests in browser stack

### ISSUE THREAD

**Issue by SandeepAppium** [AppiumTestDistribution/AppiumTestDistribution#838]
AppiumTestDistribution - 11.0.1
Attached the capabilites and Error

<img width="772" alt="caps" src="https://user-images.githubusercontent.com/81696352/113158734-aac95d00-9259-11eb-80c5-ca27c9d308ed.png">
<img width="772" alt="caps" src="https://user-images.githubusercontent.com/81696352/113158741-ac932080-9259-11eb-85a7-878dfa1f9e34.png">

Please do check and let me know, if i miss any thing.
If im running in my local, it is working as fine.From Browserstack it is not working.

Thanks in advance
@saikrishna321

**Comment by saikrishna321** [comment]
@SandeepAppium What is the error your are getting?

**Comment by SandeepAppium** [comment]
<img width="946" alt="Screenshot 2021-03-31 at 6 52 57 PM" src="https://user-images.githubusercontent.com/81696352/113195203-9ef09180-927f-11eb-9e2d-70f020352d66.png">
@saikrishna321 Sorry, added image

**Comment by saikrishna321** [comment]
Try v 12.0.0 for cucumber fixes

**Comment by SandeepAppium** [comment]
getting Error here, configFileManager = ConfigFileManager.getInstance();
getInstance method is removed, im using that method in my framework.
@saikrishna321

**Comment by saikrishna321** [comment]
@SandeepAppium Not sure why you want to use the instance of the FileManager. Please find out alternative ways

**Comment by SandeepAppium** [comment]
@saikrishna321 Thanks ,Got it. found one more issue while running Utils.
java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:128)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)

<img width="874" alt="Screenshot 2021-04-01 at 10 07 59 A@saikrishna321 " src="https://user-images.githubusercontent.com/81696352/113244196-2535c380-92d2-11eb-96b9-3def818571ba.png">
@saikrishna321

**Comment by saikrishna321** [comment]
There is a dependency clash. Show your Pom.xml

**Comment by SandeepAppium** [comment]
Yeah Got it Thanks @saikrishna321 
One more issue, When i remove ./configs/config.properties and Make the capabilities of browser stack, It is running
When i add ./configs/config.properties and try to run,it is throwing error
cofig.properties file
<img width="342" alt="Screenshot 2021-04-01 at 12 24 07 PM" src="https://user-images.githubusercontent.com/81696352/113255203-2a503e00-92e5-11eb-8b4d-a4eea101ea00.png">

capabilities.json
<img width="940" alt="Screenshot 2021-04-01 at 12 25 00 PM" src="https://user-images.githubusercontent.com/81696352/113255295-494ed000-92e5-11eb-9ca2-586f7ebb3bab.png">


Error Log:
T E S T S
-------------------------------------------------------
Running com.testsuiteexecutor.Runner
Configuring TestNG with: TestNG652Configurator
Apr 01, 2021 12:04:21 PM com.appium.utils.ConfigFileManager <clinit>
INFO: Using config file from [./configs/config.properties]
Apr 01, 2021 12:04:22 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on hub-cloud.browserstack.com
  ____              _   _   _     _     
 / ___|   _   _    (_) (_) | |_  | |__  
 \___ \  | | | |   | | | | | __| | '_ \ 
  ___) | | |_| |   | | | | | |_  | | | |
 |____/   \__,_|  _/ | |_|  \__| |_| |_|
                 |__/                   

Apr 01, 2021 12:04:22 PM com.appium.manager.ATDRunner parallelExecution
INFO: com.appium.manager.ATDRunnerTotal Number of devices detected::2

Apr 01, 2021 12:04:22 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
12:04:22.482 [main] DEBUG org.reflections.Reflections - going to scan these urls: [file:/Users/sujithreddy/Documents/EclipseWorkspace/airmeetMobileTestScripts/airmeetMobileTestScripts/target/test-classes/com/login/testscripts]
12:04:22.539 [main] INFO org.reflections.Reflections - Reflections took 49 ms to scan 1 urls, producing 2 keys and 1 values 
Apr 01, 2021 12:04:22 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
Apr 01, 2021 12:04:22 PM com.appium.manager.DeviceAllocationManager getDevices
INFO: All devices connected
Apr 01, 2021 12:04:22 PM com.appium.utils.Helpers getStream
INFO: Custom Listener not found!!
...
... TestNG 7.0.1 by CÃ©dric Beust (cedric@beust.com)
...

java.lang.NullPointerException
	at com.appium.device.DevicesByHost.lambda$getAppiumDevice$9(DevicesByHost.java:71)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.appium.device.DevicesByHost.getAppiumDevice(DevicesByHost.java:71)
	at com.appium.manager.AppiumParallelTestListener.onBeforeClass(AppiumParallelTestListener.java:141)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:167)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at com.appium.device.DevicesByHost.lambda$getAppiumDevice$9(DevicesByHost.java:71)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at com.appium.device.DevicesByHost.getAppiumDevice(DevicesByHost.java:71)
	at com.appium.manager.AppiumParallelTestListener.onBeforeClass(AppiumParallelTestListener.java:141)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:167)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at com.appium.capabilities.DesiredCapabilityBuilder.buildDesiredCapability(DesiredCapabilityBuilder.java:50)
	at com.appium.manager.AppiumDriverManager.buildDesiredCapabilities(AppiumDriverManager.java:190)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:177)
	at com.appium.manager.AppiumParallelTestListener.onTestStart(AppiumParallelTestListener.java:163)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at com.appium.capabilities.DesiredCapabilityBuilder.buildDesiredCapability(DesiredCapabilityBuilder.java:50)
	at com.appium.manager.AppiumDriverManager.buildDesiredCapabilities(AppiumDriverManager.java:190)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:177)
	at com.appium.manager.AppiumParallelTestListener.onTestStart(AppiumParallelTestListener.java:163)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Apr 01, 2021 12:04:22 PM com.context.SessionContext <clinit>
INFO: SessionContext default constructor
Apr 01, 2021 12:04:22 PM com.context.SessionContext loadReportPortalProperties
INFO: Using reportportal.properties file from src/test/resources/reportportal.properties
Apr 01, 2021 12:04:22 PM com.context.SessionContext loadReportPortalProperties
INFO: Loaded reportportal.properties file - /Users/sujithreddy/Documents/EclipseWorkspace/airmeetMobileTestScripts/airmeetMobileTestScripts/src/test/resources/reportportal.properties
Apr 01, 2021 12:04:22 PM com.context.SessionContext <clinit>
INFO: Initialized SessionContext
Apr 01, 2021 12:04:22 PM com.context.SessionContext addContext
INFO: Adding context for thread - 11
Apr 01, 2021 12:04:22 PM com.context.SessionContext addContext
INFO: Adding context for thread - 12
FAILED: validateLogin
        Check Login Functionality
java.lang.NullPointerException
	at com.appium.manager.AppiumParallelTestListener.afterInvocation(AppiumParallelTestListener.java:83)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:60)
	at org.testng.internal.BaseInvoker.runInvokedMethodListeners(BaseInvoker.java:55)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:631)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

<img width="1066" alt="Screenshot 2021-04-01 at 12 27 06 PM" src="https://user-images.githubusercontent.com/81696352/113255542-9468e300-92e5-11eb-88ac-a73d2b59e209.png">


If i remove caps.properties file, it is default and working fine
<img width="1427" alt="Screenshot 2021-04-01 at 12 28 57 PM" src="https://user-images.githubusercontent.com/81696352/113255766-d7c35180-92e5-11eb-9a2d-5547872093c1.png">


<img width="249" alt="Screenshot 2021-04-01 at 12 30 23 PM" src="https://user-images.githubusercontent.com/81696352/113255915-0b05e080-92e6-11eb-8b9f-b460c4043dfe.png">
Please  let me now if im missing something.
Many thanks

**Comment by saikrishna321** [comment]
See if this helps - https://github.com/AppiumTestDistribution/AppiumTestDistribution/blob/master/azure-pipelines.yml#L201

**Comment by SandeepAppium** [comment]
Not working, same issue

**Comment by saikrishna321** [comment]
@SandeepAppium WHat is the command your using to run when switching between config?

**Comment by SandeepAppium** [comment]
Resolved, issue is because i have changed the Runner name by mistake.
What all values should i keep in runner , Apart from Distribute.

**Comment by SandeepAppium** [comment]
i have added 3 test cases in Runner, but only one test case is executing, remaining are not executing.
Should i need to add the test cases name os something any where, which i have missed.

I can see only one test case present in parallel.xml
Attached screenshot
<img width="1438" alt="Screenshot 2021-04-03 at 1 37 42 PM" src="https://user-images.githubusercontent.com/81696352/113472674-666cd580-9482-11eb-92ef-bed448ebd2fa.png">
<img width="1404" alt="Screenshot 2021-04-03 at 1 33 41 PM" src="https://user-images.githubusercontent.com/81696352/113472678-6b318980-9482-11eb-8b9c-2cd6ecba1800.png">

Thanks @saikrishna321

**Comment by saikrishna321** [comment]
The test files should be ending with Tests

**Comment by SandeepAppium** [comment]
Parallel.xml is creating automatically, Should i need to keep in Runner as **Test.java

**Comment by SandeepAppium** [comment]
Cases are executing based on the name
Example : EnterWrongUserIdTest test case is executing, if i change the test case name to xyz.java, this test case also not executing.

**Comment by saikrishna321** [comment]
Yes, you need to rename your tests files to end with "Test"

**Comment by SandeepAppium** [comment]
Got it, Many Thanks :)
