### ISSUE TITLE
IOS Simulator: Getting No chrome browser found on device issue

### ISSUE THREAD

**Issue by Mukkesh20** [AppiumTestDistribution/AppiumTestDistribution#860]
Hi @saikrishna321 , Getting below error while running the test on iOS Simulator. 

Command to trigger the test - Platform="ios" mvn clean -Dtest=Runner test

Capabilities - 

[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:useJSONSource": true,
[debug] [BaseDriver]     "appium:webkitDebugProxyPort": 57554,
[debug] [BaseDriver]     "appium:app": "/Users/user/Downloads/sample.app",
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:clearSystemFiles": true,
[debug] [BaseDriver]     "appium:deviceName": "My-Amazing-Simulator",
[debug] [BaseDriver]     "appium:maxTypingFrequency": 10,
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:platformVersion": "14.4",
[debug] [BaseDriver]     "appium:scaleFactor": "1.0",
[debug] [BaseDriver]     "appium:shouldUseSingletonTestManager": false,
[debug] [BaseDriver]     "appium:simpleIsVisibleCheck": true,
[debug] [BaseDriver]     "appium:udid": "592D2749-284A-4502-8922-5E4E386C8F35",
[debug] [BaseDriver]     "appium:useNewWDA": true,
[debug] [BaseDriver]     "appium:usePrebuiltWDA": true,
[debug] [BaseDriver]     "appium:wdaConnectionTimeout": 80000,
[debug] [BaseDriver]     "appium:wdaLaunchTimeout": 80000,
[debug] [BaseDriver]     "appium:wdaLocalPort": 57521
[debug] [BaseDriver]   },

------------------------------------------------------------------------------------------------------------------
Console Logs: 
Jun 09, 2021 1:12:38 PM com.appium.device.HostMachineDeviceManager getChromeVersionsFor
INFO: Chrome not found on device - '592D1749-284A-4502-8922-5E4E386C8F35'
java.util.NoSuchElementException: No value present
	at java.util.OptionalInt.getAsInt(OptionalInt.java:118)
	at com.appium.device.HostMachineDeviceManager.getPathForChromeDriver(HostMachineDeviceManager.java:328)
	at com.appium.device.HostMachineDeviceManager.lambda$getAppiumDevice$8(HostMachineDeviceManager.java:295)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.appium.device.HostMachineDeviceManager.getAppiumDevices(HostMachineDeviceManager.java:284)
	at com.appium.device.HostMachineDeviceManager.getDevicesByIP(HostMachineDeviceManager.java:150)
	at com.appium.device.HostMachineDeviceManager.getDevices(HostMachineDeviceManager.java:213)
	at com.appium.device.HostMachineDeviceManager.initializeDevicesByHost(HostMachineDeviceManager.java:78)
	at com.appium.device.HostMachineDeviceManager.<init>(HostMachineDeviceManager.java:46)
	at com.appium.device.HostMachineDeviceManager.getInstance(HostMachineDeviceManager.java:68)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:23)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:34)
	at com.appium.manager.ATDRunner.<init>(ATDRunner.java:31)
	at com.sample.growth.tests.crypto.Runner.testRunner(Runner.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by saikrishna321** [comment]
This issue is fixed in master. Please use the master commit

**Comment by Mukkesh20** [comment]
Hi @saikrishna321 .. Currently I'm using saikrishna321 maven dependency - 

<dependency>
		   <groupId> com.github.saikrishna321 </groupId>
		   <artifactId >AppiumTestDistribution </artifactId>
		   <version>12.0.2</version>
</dependency>

Can i get maven dependency for the latest commit. I used the below dependencies one by one but it throws "Missing artifact com.github.AppiumTestDistribution:AppiumTestDistribution:jar:latest_commit" error.

<dependency>
		    <groupId>com.github.AppiumTestDistribution</groupId>
		    <artifactId>AppiumTestDistribution</artifactId>
		    <version>latest_commit</version>
</dependency>

<dependency>
		    <groupId>com.github.AppiumTestDistribution</groupId>
		    <artifactId>AppiumTestDistribution</artifactId>
		    <version>d2a0aba</version>
</dependency>

**Comment by saikrishna321** [comment]
Fixed in v12.0.3
