### ISSUE TITLE
How to Run Runner Class with Platform Name?

### ISSUE THREAD

**Issue by chetanJTH** [AppiumTestDistribution/AppiumTestDistribution#868]
I have downloaded zip and all dependency from pom.xml.
when I run the command `Platform=android mvn clean -Dtest=Runner` it gives an error.
please check the image to know about an error. 

![image](https://user-images.githubusercontent.com/48850556/125390254-2e015f80-e3c0-11eb-85b0-5255daaad061.png)

environment 
ATD Version: 12.0.2
appium version: 1.20
os: windows 10
Real Device: realme
Example command: Platform=android mvn clean -Dtest=Runner

**Comment by saikrishna321** [comment]
Can you please share the logs

**Comment by chetanJTH** [comment]
appium does not even start. how would I get logs? @saikrishna321

**Comment by chetanJTH** [comment]
@saikrishna321: will you please help me to understand this issue?

**Comment by saikrishna321** [comment]
Sorry for delay response. You need to run the command from the root of the project. Please refer the azure yaml file

**Comment by chetanJTH** [comment]
I am not getting the azure yaml file but I am running the test from the root of the project @saikrishna321

**Comment by saikrishna321** [comment]
Run the command from command line and not from IntelliJ and give a try

**Comment by chetanJTH** [comment]
from which folder or file i should run the command? @saikrishna321

**Comment by saikrishna321** [comment]
From the root of the project

**Comment by chetanJTH** [comment]
@saikrishna321: 'Platform' is not recognized as an internal or external command

![image](https://user-images.githubusercontent.com/48850556/126105248-935106db-4127-4df7-9e38-4cc578f741b5.png)

**Comment by chetanJTH** [comment]
@saikrishna321 please check

**Comment by saikrishna321** [comment]
Please set Platform as environment. google to find out on how to set environment variables for windows

**Comment by chetanJTH** [comment]
@saikrishna321 please check

![image](https://user-images.githubusercontent.com/48850556/126735828-f42e7735-0610-41b1-ac5a-6175e834ff2b.png)
![image](https://user-images.githubusercontent.com/48850556/126735861-9f2c330f-f8cf-4c7b-be92-57d3039e1cee.png)

**Comment by saikrishna321** [comment]
You need to set Platform=android in env

**Comment by chetanJTH** [comment]
@saikrishna321 I have set the platform as an android in env and getting the same error.

**Comment by chetanJTH** [comment]
@saikrishna321 please check logs. i was able to run through cmd. i want to understand this framework. i don't get why app keep launching.

<script src="https://gist.github.com/chetanJTH/82a6a3dae84cdc8bb14e66abb63b913e.js"></script>

**Comment by saikrishna321** [comment]
Logs looks fine. What you mean by app keeps launching? Can you please elaborate

**Comment by chetanJTH** [comment]
my mistake. the app was launching before every test class. can we stop that? and how can we run test through testNG.xml?

**Comment by chetanJTH** [comment]
@saikrishna321 i am getting issue while running test from testNG.xml

```
Aug 19, 2021 11:55:24 AM com.appium.manager.LocalAppiumManager startAppiumServer
INFO: LocalAppiumManagerStarting Appium Server on Localhost
Picking Default Path for AppiumServiceBuilder
uncaughtException: EPERM: operation not permitted, stat 'C:\Users\HP\Downloads\AppiumTestDistribution-master\AppiumTestDistribution-master\target\appiumlogs\appium_logs.txt'
Error: EPERM: operation not permitted, stat 'C:\Users\HP\Downloads\AppiumTestDistribution-master\AppiumTestDistribution-master\target\appiumlogs\appium_logs.txt'
C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:307
      throw ex;
      ^

NodeError: write after end
    at writeAfterEnd (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:261:12)
    at PassThrough.Writable.write (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    at File.log (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\transports\file.js:185:34)
    at File._write (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\index.js:103:17)
    at doWrite (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at File.Writable.write (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DerivedLogger.ondata (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DerivedLogger.emit (events.js:387:35)
    at addChunk (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at DerivedLogger.Readable.push (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at DerivedLogger.Transform.push (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at DerivedLogger._transform (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\winston\lib\winston\logger.js:305:12)
    at DerivedLogger.Transform._read (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:164:83)
Emitted 'error' event on PassThrough instance at:
    at errorOrDestroy (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\internal\streams\destroy.js:98:101)
    at writeAfterEnd (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:263:3)
    at PassThrough.Writable.write (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_writable.js:305:21)
    [... lines matching original stack trace ...]
    at DerivedLogger.Transform._read (C:\Users\HP\AppData\Roaming\npm\node_modules\appium\node_modules\readable-stream\lib\_stream_transform.js:177:10)
```

**Comment by saikrishna321** [comment]
@chetanJTH ATD takes care of orchestrating the runner. So you entry should always be the runner. Not through TestNG.xml. You are using ATD incorrectly. Please refer ReadMe and wiki.

It will great if you can use the Discussion.
