### ISSUE TITLE
java.nio.file.InvalidPathException: Illegal char <:> at index 2: bs://<app_url> 

### ISSUE THREAD

**Issue by Siddh010** [AppiumTestDistribution/AppiumTestDistribution#914]
ATD version 12.0.3   
Issue while reading app url for browserstack 

Capabalities: 
{
  "android": {
    "automationName": "UIAutomator2",
    "project": "ATD",
    
    "app": {
      "local": "https://github.com/shridharkalagi/AppiumSample/raw/master/VodQA.apk",
       "cloud": "bs://2523e1fed2854215d12ccb6a190ba1wb1a5ee279"
    },
    "noSign": true
  },
  "iOS": {
    "platformName": "iOS",
    "app": {
      "simulator": "https://github.com/saikrishna321/AppiumTestDistribution/blob/master/VodQAReactNative.zip?raw=true",
      "cloud": "bs://c45ee418d63142cea1f288e561fc970cf05a5a7d"
    },
    "deviceName": "iPhone",
    "wdaLaunchTimeout": 80000,
    "wdaConnectionTimeout": 80000,
    "preventWDAAttachments": true,
    "clearSystemFiles": true,
    "shouldUseSingletonTestManager": false,
    "simpleIsVisibleCheck": true,
    "maxTypingFrequency": 10
  },
  "cloud": {
    "android": [
      {
        "deviceName": "Google Pixel 3 XL",
        "osVersion": "9.0"
      }
    ]
  },
  "hostMachines": [
    {
     "isCloud": true,
      "machineIP": "hub-cloud.browserstack.com",
      "cloudName": "browserstack"
    }
  ]
}
Error message :-

CucumberScenarioReporterListener
Dec 29, 2021 5:35:19 PM com.appium.utils.ConfigFileManager <clinit>
INFO: Using config file from [./configs/config.properties]
ThreadID: 1: CucumberScenarioListener
Dec 29, 2021 5:35:20 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on hub-cloud.browserstack.com
log4j:WARN No appenders could be found for logger (rp.org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
runStartedHandler
ThreadID: 1: beforeSuite: 
ThreadID: 1: in overridden scenarios
[[Ljava.lang.Object;@2577d6c8
Dec 29, 2021 5:35:21 PM com.appium.manager.DeviceAllocationManager allocateDevice
INFO: Allocated Device com.appium.manager.AppiumDevice@54465e37 for Execution
caseStartedHandler: As user i should be able to login in with valid credentials
ThreadID: 18: beforeScenario: for scenario: As user i should be able to login in with valid credentials
java.nio.file.InvalidPathException: Illegal char <:> at index 2: bs://2523e1fed2854215d12ccb6a190ba1wb1a5ee279
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at com.appium.capabilities.DesiredCapabilityBuilder.capabilityObject(DesiredCapabilityBuilder.java:91)
	at com.appium.capabilities.DesiredCapabilityBuilder.lambda$desiredCapabilityForCloud$0(DesiredCapabilityBuilder.java:67)
	at java.util.HashMap$KeySet.forEach(Unknown Source)
	at com.appium.capabilities.DesiredCapabilityBuilder.desiredCapabilityForCloud(DesiredCapabilityBuilder.java:66)
	at com.appium.capabilities.DesiredCapabilityBuilder.buildDesiredCapability(DesiredCapabilityBuilder.java:55)
	at com.appium.manager.AppiumDriverManager.buildDesiredCapabilities(AppiumDriverManager.java:190)
	at com.appium.manager.AppiumDriverManager.startAppiumDriverInstance(AppiumDriverManager.java:177)
	at com.cucumber.listener.CucumberScenarioListener.allocateDeviceAndStartDriver(CucumberScenarioListener.java:62)
	at com.cucumber.listener.CucumberScenarioListener.caseStartedHandler(CucumberScenarioListener.java:97)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
	at io.cucumber.core.runtime.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:66)
	at io.cucumber.core.runner.TestCase.emitTestCaseStarted(TestCase.java:228)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:92)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
	at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$0(TestNGCucumberRunner.java:116)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:113)
	at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

**Comment by saikrishna321** [comment]
@Siddh010 I don't have a windows machine to test this. Can you please debug and raise a PR happy to help.

**Comment by Siddh010** [comment]
I am getting this issue with [PageObject ](https://github.com/AppiumTestDistribution/PageObjectPatternAppium)  project and not with AppiumTestDistribution

**Comment by Siddh010** [comment]
I changes json  Key value for app and now fixed from  "cloud": "bs://c45ee418d63142cea1f2989h561fc970cf05a5a7d" to "device ": "bs://c45ee418d63142cea1f288e561fc934398f05a5a7d"
