### ISSUE TITLE
Headspin session is not being created , bundleid for ios and 'app' option is required for reinstall for android

### ISSUE THREAD

**Issue by AnilPatidar** [AppiumTestDistribution/AppiumTestDistribution#938]
due to these changes, Headspin execution is not happening because , it does not take bundleId in the capabilities, before these changes we used have "appium:bundleId": "valid id" in the capabilities . please check the issue, after reverting back to old version, our execution worked fine

**android :**  org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'ip-#.#.internal', ip: '10.$.#.#', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.12.1.el7.x86_64', java.version: '11.0.11'
    Driver info: driver.version: AndroidDriver
    remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'app' option is required for reinstall
        at getResponseForW3CError (/home/hs/headspinio-pboxagent/appium/1.22.3/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
        at asyncHandler (/home/hs/headspinio-pboxagent/appium/1.22.3/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
    System info: host: 'ip-#.#.internal', ip: '10.$.#.#', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.12.1.el7.x86_64', java.version: '11.0.11'
    Driver info: driver.version: AndroidDriver
    	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)

**ios capabilities :**

2-04-19 16:47:39:062 - [debug] [BaseDriver] Creating session with W3C capabilities: {
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "alwaysMatch": {
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "platformName": "ios",
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "browserName": "",
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:shouldUseSingletonTestManager": false,
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:wdaConnectionTimeout": 240000,
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:name": "testName",
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:startIWDP": true,
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:platformVersion": "11.3.1",
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:xcodeSigningId": "iPhone Developer",
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:maxTypingFrequency": 10,
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "appium:permission": {
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "com.xys.abc.ios": {
2022-04-19 16:47:39:062 - [debug] [BaseDriver] "location": "inuse"
2022-04-19 16:47:39:063 - [debug] [BaseDriver] }
2022-04-19 16:47:39:063 - [debug] [BaseDriver] },
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:xcodeOrgId": "valid id",
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:webDriverAgentUrl": "http://localhost:1878/",
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:autoAcceptAlerts": true,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:noReset": false,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:automationName": "XCUITest",
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:newCommandTimeout": 100000,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:udid": "valid udid",
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:_comment": "some valid url",
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:autoLaunch": true,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:webviewConnectRetries": 5,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:wdaLaunchTimeout": 240000,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:preventWDAAttachments": true,
2022-04-19 16:47:39:063 - [debug] [BaseDriver] "appium:device": "valid name",
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:deviceName": "valid name",
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:autoGrantPermissions": true,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:fullContextList": true,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:clearSystemFiles": true,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:webkitResponseTimeout": 50000,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:simpleIsVisibleCheck": true,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:safariLogAllCommunication": true,
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "appium:chromedriverExecutableDir": "valid path"
2022-04-19 16:47:39:064 - [debug] [BaseDriver] },
2022-04-19 16:47:39:064 - [debug] [BaseDriver] "firstMatch": [
2022-04-19 16:47:39:064 - [debug] [BaseDriver] {}
2022-04-19 16:47:39:064 - [debug] [BaseDriver] ]
2022-04-19 16:47:39:064 - [debug] [BaseDriver] }

**Comment by saikrishna321** [comment]
Can you please share your capabilities.json file

**Comment by AnilPatidar** [comment]
{
   "android":{
      "platformName":"android",
      "platformVersion":"7.1.1",
      "browserName":"android.browser.app",
      "noSign":true,
      "autoAcceptAlerts":true,
      "automationName":"UIAutomator2",
      "newCommandTimeout":600000,
      "adbExecTimeout":60000,
      "androidInstallTimeout":600000,
      "skipServerInstallation":false,
      "noReset":false,
      "autoGrantPermissions":true,
      "appPackage":"com.##.android.##”,
      "appActivity”:”##.##.##Activity dockerEnvData -e pocoEnvData",
      "appium:chromeOptions":{
         "w3c":false
      },
      "headspin:capture.video":true,
      "app":{
         "local":"android.temp.app"
      }
   },
   "iOS":{
      "platformName":"iOS",
      "permission":{
         "com.games24x7.rummycircle.ios":{
            "location":"inuse"
         }
      },
      "deviceName":"Rummy's iPad",
      "browserName":"",
      "platformVersion":"11.3.1",
      "wdaLaunchTimeout":240000,
      "wdaConnectionTimeout":240000,
      "preventWDAAttachments":true,
      "clearSystemFiles":true,
      "shouldUseSingletonTestManager":false,
      "simpleIsVisibleCheck":true,
      "maxTypingFrequency":10,
      "autoGrantPermissions":true,
      "autoAcceptAlerts":true,
      "automationName":"XCUITest",
      "xcodeOrgId”:”#######”,
      "xcodeSigningId":"iPhone Developer",
      "noReset":false,
      "webviewConnectRetries":5,
      "webkitResponseTimeout":50000,
      "startIWDP":true,
      "newCommandTimeout":100000,
      "safariLogAllCommunication":true,
      "useNewWDA":true,
      "_comment":"mec://helper?url=https://#.com",
      "fullContextList":true,
      "headspin:capture.video":true,
      "headspin:appId":"8b5ff2fc-e54e-47dc-a7d6-142899c2dd0f",
      "bundleId":"com.##.ios"
   },
   "cloud":{
      "android":[
         {
            "deviceName":"device1",
            "udid":"00008###-001###C226840###”
         }
      ],
      "iOS":[
         {
            "deviceName":"3530#41021856##”,
            "udid":"00008###-001###C226840###”
         }
      ]
   },
   "hostMachines":[
      {
         "isCloud":true,
         "machineIP”:”##.com:7002/v0/##”,
         "cloudName":"headspin"
      }
   ]
}

**Comment by AnilPatidar** [comment]
@saikrishna321 can we have new ATD version , the last release was  on 23 Jul 2021 and later we pushed so many changes, like headspin support etc.

**Comment by saikrishna321** [comment]
Will make a release tonight

**Comment by saikrishna321** [comment]
@anandbagmar Any idea on this issue ?

**Comment by anandbagmar** [comment]
@AnilPatidar - can you please check once with the latest ATD version - 723c15c425 and let us know if you still see the same problem?

**Comment by AnilPatidar** [comment]
Sure let me try it
