### ISSUE TITLE
How to configure Lamda Test using this appium distribution framework

### ISSUE THREAD

**Issue by AppiumUser321** [AppiumTestDistribution/AppiumTestDistribution#961]
@saikrishna321 Pls help in configuring Lamda Test for my project
Below details added
**In Json file added the host machine**
  "hostMachines": [
    {
      "isCloud": true,
      "machineIP": "mobile-hub.lambdatest.com/wd/hub"
    }

**And running the command** 
Platform=android CLOUD_USER=LTUserName CLOUD_KEY=LTKey mvn clean -Dtest=Runner test

**Getting the below error while running the script**
[INFO] Running com.testsuiteexecutor.Runner2
Jul 06, 2022 6:01:15 PM com.appium.utils.ConfigFileManager <clinit>
INFO: Using config file from [./configs/config.properties]
Jul 06, 2022 6:01:15 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on mobile-hub.lambdatest.com/wd/hub
org.json.JSONException: JSONObject["local"] not found.
	at org.json.JSONObject.get(JSONObject.java:572)
	at org.json.JSONObject.getString(JSONObject.java:859)
	at com.appium.utils.ArtifactsUploader.getArtifactForHost(ArtifactsUploader.java:79)
	at com.appium.utils.ArtifactsUploader.initializeArtifacts(ArtifactsUploader.java:41)
	at com.appium.manager.DeviceAllocationManager.<init>(DeviceAllocationManager.java:26)
	at com.appium.manager.DeviceAllocationManager.getInstance(DeviceAllocationManager.java:36)
	at com.appium.manager.ATDRunner.<init>(ATDRunner.java:46)
	at com.testsuiteexecutor.Runner2.testCukesRunner(Runner2.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

**Comment by saikrishna321** [comment]
@AppiumUser321 We don't support LamdaTest parallel run yet. Please raise a PR. Happy to review and merge.

**Comment by AppiumUser321** [comment]
@saikrishna321 i have tried , but not able to doit. can you pls help me.
im new to automation.

**Comment by Jitu1888** [comment]
@AppiumUser321 i can help u out

**Comment by saikrishna321** [comment]
Please try latest version.
